import test from 'node:test';
import assert from 'node:assert/strict';
import { buildStreetSkeleton,nearestStreetEdge,attachAddresses,connectedComponents,graphQuality,buildBerlinCandidate } from '../tools/berlin-graph-lib.mjs';

function importedFixture(){return{metadata:{source:'fixture'},streets:[
  {name:'Alpha Straße',streetKey:'alpha straße',streetNumber:'001',sourceId:'a',fromNode:'A0',toNode:'A2',lines:[[[0,0],[50,0],[100,0]]]},
  {name:'Beta Straße',streetKey:'beta straße',streetNumber:'002',sourceId:'b',fromNode:'B0',toNode:'B2',lines:[[[50,-50],[50,0],[50,50]]]},
  {name:'Gamma Straße',streetKey:'gamma straße',streetNumber:'003',sourceId:'c',fromNode:'A2',toNode:'G2',lines:[[[100.7,0.3],[140,0],[180,0]]]}
],addresses:[
  {street:'Alpha Straße',streetKey:'alpha straße',streetNumber:'001',houseNumber:'10',postcode:'10000',x:20,y:2,sourceId:'p1'},
  {street:'ALPHA STRASSE',streetKey:'alpha straße',streetNumber:null,houseNumber:'22',postcode:'10000',x:72,y:-3,sourceId:'p2'},
  {street:'Beta Straße',streetKey:'beta straße',streetNumber:'002',houseNumber:'5',postcode:'10000',x:52,y:35,sourceId:'p3'},
  {street:'Gamma Straße',streetKey:'gamma straße',streetNumber:'003',houseNumber:'8',postcode:'10000',x:145,y:1,sourceId:'p4'}
]};}

test('street skeleton uses official Detailnetz node IDs before coordinate fuzz',()=>{const graph=buildStreetSkeleton(importedFixture().streets,{snapTolerance:.1});const official=graph.nodes.filter(n=>n.sourceNodeId==='A2');assert.equal(official.length,1);assert.equal(connectedComponents(graph).length,2);const alphaGamma=graph.edges.filter(e=>['Alpha Straße','Gamma Straße'].includes(e.streetName));assert.ok(alphaGamma.some(e=>e.a===official[0].id||e.b===official[0].id));});

test('street skeleton still snaps ordinary shared intersection vertices',()=>{const fixture=importedFixture();fixture.streets=fixture.streets.slice(0,2).map(s=>({...s,fromNode:null,toNode:null}));const graph=buildStreetSkeleton(fixture.streets,{snapTolerance:1});const center=graph.nodes.filter(n=>Math.hypot(n.x-50,n.y)<.01);assert.equal(center.length,1);assert.equal(connectedComponents(graph).length,1);});

test('nearest address attachment can require official street number',()=>{const skeleton=buildStreetSkeleton(importedFixture().streets,{snapTolerance:1}),address={street:'Wrong display',streetKey:'wrong display',streetNumber:'001',houseNumber:'99',x:50,y:8};const match=nearestStreetEdge(address,skeleton.nodes,skeleton.edges,{matchMode:'number',maxDistance:20});assert.ok(match);assert.equal(match.edge.streetNumber,'001');assert.equal(match.matchKind,'number');});

test('address attachment prefers street number then canonical name before geometry',()=>{const imported=importedFixture(),skeleton=buildStreetSkeleton(imported.streets,{snapTolerance:1}),graph=attachAddresses(skeleton,imported.addresses,{maxDistance:8});assert.equal(graph.unmatched.length,0);assert.equal(graph.matchedCount,4);assert.deepEqual(graph.matchCounts,{number:3,name:1,fallback:0});const addressNodes=graph.nodes.filter(n=>n.kind==='address');assert.equal(addressNodes.length,4);assert.equal(addressNodes.find(n=>n.sourceId==='p2').matchKind,'name');assert.ok(addressNodes.every(n=>Number.isInteger(n.anchorId)));assert.ok(graph.edges.some(e=>e.kind==='address-link'));});

test('official street number wins over a geometrically closer parallel street',()=>{const skeleton=buildStreetSkeleton([{name:'Right Straße',streetKey:'right straße',streetNumber:'100',lines:[[[0,0],[100,0]]]},{name:'Wrong Straße',streetKey:'wrong straße',streetNumber:'200',lines:[[[0,3],[100,3]]]}],{snapTolerance:.1}),address={street:'Right Straße',streetKey:'right straße',streetNumber:'100',houseNumber:'5',x:50,y:2.8},graph=attachAddresses(skeleton,[address],{maxDistance:5});const node=graph.nodes.find(n=>n.kind==='address');assert.equal(node.matchKind,'number');assert.equal(node.streetNumber,'100');const link=graph.edges.find(e=>e.kind==='address-link');const anchor=graph.nodes[link.a];assert.ok(anchor.y<1,'should attach to official street, not closer parallel road');});

test('geometric fallback stays explicit and can fail candidate quality gate',()=>{const imported=importedFixture();imported.addresses.push({street:'Unknown Road',streetKey:'unknown road',houseNumber:'1',x:48,y:2,sourceId:'fallback'});const candidate=buildBerlinCandidate(imported,{snapTolerance:1,maxDistance:8,minAddressMatch:.7,maxFallbackShare:.1});assert.equal(candidate.metadata.addressMatchKinds.fallback,1);assert.equal(candidate.nodes.find(n=>n.sourceId==='fallback').matchKind,'fallback');assert.equal(candidate.metadata.quality.valid,false);assert.ok(candidate.metadata.quality.errors.some(error=>error.includes('fallback match share')));});

test('candidate graph quality reports fragmentation and address coverage rather than hiding it',()=>{const imported=importedFixture(),candidate=buildBerlinCandidate(imported,{snapTolerance:1,maxDistance:8,maxComponents:3,minLargestShare:.55,minAddressMatch:.9,maxFallbackShare:.1});assert.equal(candidate.metadata.candidate,true);assert.equal(candidate.metadata.matchedAddresses,4);assert.equal(candidate.metadata.unmatchedAddresses,0);assert.equal(candidate.metadata.quality.addressMatch,1);assert.equal(candidate.metadata.quality.fallbackShare,0);const fragmented={nodes:[{id:0},{id:1},{id:2}],edges:[{a:0,b:1}]},quality=graphQuality(fragmented,{maxComponents:1,minLargestShare:.9,minAddressMatch:0,maxFallbackShare:1});assert.equal(quality.valid,false);assert.ok(quality.errors.some(error=>error.includes('components')));});

test('far unmatched addresses remain explicit for importer diagnostics',()=>{const imported=importedFixture();imported.addresses.push({street:'Missing Straße',houseNumber:'1',x:500,y:500,sourceId:'far'});const candidate=buildBerlinCandidate(imported,{snapTolerance:1,maxDistance:8,minAddressMatch:.7,maxFallbackShare:.1,maxComponents:3,minLargestShare:.5});assert.equal(candidate.metadata.matchedAddresses,4);assert.equal(candidate.metadata.unmatchedAddresses,1);assert.equal(candidate.unmatchedAddresses[0].sourceId,'far');assert.ok(candidate.metadata.quality.addressMatch>.79&&candidate.metadata.quality.addressMatch<.81);});