import test from 'node:test';
import assert from 'node:assert/strict';
import { RNG, hashSeed } from '../src/rng.js';
import { shortestPath } from '../src/graph.js';
import { BERLIN } from '../src/berlin.js';
import { Game, DELIVERY_TYPES, PERSONALITIES, EXPERIENCE, RADIO_CHANNELS } from '../src/game.js';

test('seed hashing and RNG are deterministic',()=>{assert.equal(hashSeed('BERLIN-42'),hashSeed('BERLIN-42'));const a=new RNG('same-seed'),b=new RNG('same-seed');assert.deepEqual(Array.from({length:8},()=>a.next()),Array.from({length:8},()=>b.next()));});

test('Berlin skeleton keeps recognizable relative landmark positions and named Spree bridges',()=>{const byId=new Map(BERLIN.landmarks.map((l)=>[l.id,l]));assert.ok(byId.get('zoo').x<byId.get('brandenburg').x);assert.ok(byId.get('alex').x>byId.get('brandenburg').x);assert.ok(byId.get('mauerpark').y<byId.get('alex').y);assert.ok(byId.get('tempelhofer').y>byId.get('checkpoint').y);assert.ok(byId.get('eastside').x>byId.get('alex').x);assert.ok(BERLIN.bridges.length>=3);assert.ok(BERLIN.bridges.some((b)=>b.name==='Oberbaumbrücke'));});

test('same seed creates same Berlin variation, roster, goals and jobs',()=>{const a=new Game({seed:'BERLIN-TEST'}),b=new Game({seed:'BERLIN-TEST'});assert.equal(a.runTrait.id,b.runTrait.id);assert.deepEqual(a.nodes.map((n)=>[n.id,n.x,n.y,n.districtId]),b.nodes.map((n)=>[n.id,n.x,n.y,n.districtId]));assert.deepEqual(a.couriers.map((c)=>[c.name,c.personality.id,c.experience.level,c.homeDistrict]),b.couriers.map((c)=>[c.name,c.personality.id,c.experience.level,c.homeDistrict]));assert.deepEqual(a.goals,b.goals);assert.deepEqual(a.activeDeliveries(),b.activeDeliveries());});

test('Berlin network is fully routable across procedural seeds',()=>{for(let i=0;i<50;i+=1){const game=new Game({seed:`ROUTE-${i}`});for(const node of game.nodes){const path=shortestPath(game.nodes,game.edges,game.depotNodeId,node.id,game.edgeCost.bind(game));assert.ok(path.length>0,`seed ${i} cannot reach ${node.id}`);}}});

test('dispatcher uses bandwidth channels instead of assigning riders',()=>{const game=new Game({seed:'RADIO'});assert.equal(typeof game.assign,'undefined');const[first,second,third]=game.activeDeliveries();assert.equal(game.setChannel(first.id,'priority'),true);assert.equal(game.radioUsed(),RADIO_CHANNELS.priority.cost);assert.equal(game.setChannel(second.id,'open'),true);assert.equal(game.setChannel(third.id,'local'),true);assert.equal(game.radioUsed(),game.radioSlots);game.spawnDelivery();const fourth=game.activeDeliveries().find((d)=>!d.called);assert.equal(game.setChannel(fourth.id,'open'),false);assert.equal(game.setChannel(first.id,'open'),true);assert.equal(game.radioUsed(),3);assert.equal(game.setChannel(fourth.id,'open'),true);});

test('priority and local channels influence but do not directly assign',()=>{const game=new Game({seed:'CHANNEL-BIAS'});const rider=game.couriers[0];const[a,b]=game.activeDeliveries();game.setChannel(a.id,'open');game.setChannel(b.id,'priority');const openScore=game.courierChoiceScore(rider,a,false);const priorityAsOpen=game.courierChoiceScore(rider,b,false)-.55;const priorityScore=game.courierChoiceScore(rider,b,false);assert.ok(priorityScore>priorityAsOpen);assert.equal(a.courierId,null);assert.equal(b.courierId,null);assert.ok(Number.isFinite(openScore));});

test('idle rider visibly deliberates before autonomously claiming a call',()=>{const game=new Game({seed:'CHOICE'});const delivery=game.activeDeliveries()[0];game.setChannel(delivery.id,'open');const rider=game.couriers[0];rider.decisionAt=0;game.update(.05);assert.ok(rider.deliberation,'rider should enter deliberation state');assert.equal(rider.phase,'idle');assert.ok(game.deliberationProgress(rider)>=0);let guard=0;while(delivery.status==='waiting'&&guard++<100)game.update(.1);assert.equal(delivery.status,'claimed');assert.ok(delivery.courierId);});

test('riders have personality and experience models',()=>{const game=new Game({seed:'ROSTER'});for(const rider of game.couriers){assert.ok(PERSONALITIES.some((p)=>p.id===rider.personality.id));assert.ok(EXPERIENCE.some((e)=>e.level===rider.experience.level));assert.ok(rider.personality.desc.length>5);assert.ok(rider.experience.level>=1&&rider.experience.level<=4);}});

test('delivery type generation is independent of district identity',()=>{const game=new Game({seed:'INDEPENDENT-SPAWNS'}),seen=new Map(game.districts.map((d)=>[d.id,new Set()]));for(let i=0;i<700;i+=1){game.deliveries=[];game.spawnDelivery();const d=game.deliveries[0],district=game.nodeById(d.pickupId).districtId;seen.get(district)?.add(d.type);}const observed=[...seen.values()].filter((set)=>set.size>0);assert.ok(observed.length>=7);for(const set of observed)assert.ok(set.size>=3,'a district became too tightly coupled to job type');assert.equal(Object.keys(DELIVERY_TYPES).length,6);});

test('bridge goals advance only when the completed route actually uses the target bridge',()=>{const game=new Game({seed:'BRIDGE-GOAL'});const bridgeGoal={id:'test',type:'bridge',targetId:'oberbaumbruecke',label:'Use Oberbaum',detail:'',progress:0,target:2,reward:1,complete:false};game.goals=[bridgeGoal];const bridgeEdge=game.edges.find((e)=>e.bridgeId==='oberbaumbruecke');assert.ok(bridgeEdge);const delivery={pickupId:'goerlitzer',dropoffId:'oberbaum',edgesTraversed:[bridgeEdge.id]};game.updateGoals(delivery);assert.equal(bridgeGoal.progress,1);delivery.edgesTraversed=[];game.updateGoals(delivery);assert.equal(bridgeGoal.progress,1);});

test('temporary road event changes travel cost and then clears',()=>{const game=new Game({seed:'EVENT'});game.nextEventAt=.5;game.update(.01);game.elapsed=.5;game.updateRoadEvent();assert.ok(game.currentEvent);if(game.currentEvent.state==='forecast'){game.elapsed=game.currentEvent.startsAt;game.updateRoadEvent();}assert.equal(game.currentEvent.state,'active');const affected=game.edges.find((e)=>game.currentEvent.edgeIds.includes(e.id));assert.ok(affected.eventMultiplier<1);const activeCost=game.edgeCost(affected);affected.eventMultiplier=1;const normalCost=game.edgeCost(affected);assert.ok(activeCost>normalCost);affected.eventMultiplier=game.currentEvent.factor;game.elapsed=game.currentEvent.endsAt+.01;game.updateRoadEvent();assert.equal(game.currentEvent,null);assert.equal(affected.eventMultiplier,1);});

test('post-shift review distinguishes never-called and called-unclaimed failures',()=>{const game=new Game({seed:'REVIEW'});const[never,called]=game.activeDeliveries();never.deadlineAt=0;game.failDelivery(never);game.setChannel(called.id,'open');called.deadlineAt=0;game.failDelivery(called);const review=game.dispatchReview();assert.equal(review.neverCalled,1);assert.equal(review.calledUnclaimed,1);assert.ok(review.advice.length>0);assert.ok(Array.isArray(review.timeline));});

test('goal progress is driven by completed endpoints, not spawn tables',()=>{const game=new Game({seed:'GOALS'}),goal=game.goals.find((g)=>g.type==='landmark'),targetNode=game.nodes.find((n)=>n.landmarkId===goal.targetId),other=game.nodes.find((n)=>n.id!==targetNode.id&&n.id!==game.depotNodeId),before=goal.progress;game.updateGoals({pickupId:targetNode.id,dropoffId:other.id,edgesTraversed:[]});assert.equal(goal.progress,before+1);});
