import test from 'node:test';
import assert from 'node:assert/strict';
import { Game,SCHEDULED_SPECIAL,SPECIAL_CONTRACTS } from '../src/game.js';

function scheduledScenario(seed='WINDOW'){const g=new Game({seed});g.cityLevel=2;g.deliveries=[];const pickup=g.playableAddressNodes()[12],dropoff=g.playableAddressNodes().find(n=>n.id!==pickup.id&&g.routeBetween(pickup.id,n.id).length>3);assert.ok(pickup&&dropoff);assert.equal(g.spawnDelivery({pickupId:pickup.id,dropoffId:dropoff.id,typeKey:'document',special:SCHEDULED_SPECIAL}),true);const d=g.deliveries.at(-1),r=g.couriers[0];r.nodeId=pickup.id;r.x=pickup.x;r.y=pickup.y;r.phase='idle';r.path=[];r.pathIndex=0;return{g,d,r};}

test('scheduled pickup is a rare level-two special contract with a future ready time',()=>{assert.ok(SPECIAL_CONTRACTS.some(item=>item.id==='scheduled'));assert.equal(SCHEDULED_SPECIAL.minLevel,2);const{g,d}=scheduledScenario();assert.equal(d.specialId,'scheduled');assert.equal(d.specialLabel,'WINDOW');assert.ok(d.pickupReadyAt>d.createdAt);assert.ok(d.pickupReadyAt-d.createdAt>=14);assert.ok(d.pickupReadyAt-d.createdAt<=30);assert.ok(d.deadlineAt>d.pickupReadyAt+20);assert.match(d.specialDesc,/opens|Pickup/i);});

test('rider may volunteer early but waits at pickup until the client window opens',()=>{const{g,d,r}=scheduledScenario('WINDOW-WAIT');assert.equal(g.setChannel(d.id,'open'),true);assert.equal(g.claim(r,d),true);assert.equal(r.phase,'waiting-pickup');assert.equal(d.pickedUp,false);assert.equal(r.radioOn,true);assert.ok(r.waitUntil>d.createdAt);const before=d.pickedUp;for(let i=0;i<Math.ceil((d.pickupReadyAt-g.elapsed)*10)-1;i++)g.update(.1);assert.equal(d.pickedUp,before);while(g.elapsed<d.pickupReadyAt+.2)g.update(.1);assert.equal(d.pickedUp,true);assert.equal(r.phase,'dropoff');});

test('waiting at a scheduled pickup occupies the rider and does not enable pre-assignment',()=>{const{g,d,r}=scheduledScenario('WINDOW-CAPACITY');g.setChannel(d.id,'priority');g.claim(r,d);const nextDrop=g.playableAddressNodes().find(n=>n.id!==d.dropoffId&&g.routeBetween(d.dropoffId,n.id).length>1);assert.ok(nextDrop);assert.equal(g.spawnDelivery({pickupId:d.dropoffId,dropoffId:nextDrop.id,typeKey:'parcel',special:false}),true);const other=g.deliveries.at(-1),availability=g.courierAvailability(r,other),horizon=Math.ceil(availability.arrivalIn)+1,outlook=g.deliveryRiderOutlook(other,{limit:6,horizon}).find(item=>item.rider.id===r.id);assert.equal(r.phase,'waiting-pickup');assert.equal(availability.state,'busy');assert.equal(availability.availableNow,false);assert.ok(availability.readyIn>0);assert.ok(Number.isFinite(availability.arrivalIn));assert.ok(outlook);assert.equal(outlook.availableNow,false);g.setChannel(other.id,'open');assert.equal(g.claim(r,other),false);assert.equal(r.deliveryId,d.id);});

test('scheduled wait contributes a stable mid-task progress state and ETA',()=>{const{g,d,r}=scheduledScenario('WINDOW-PROGRESS');g.setChannel(d.id,'open');g.claim(r,d);assert.equal(g.courierTaskProgress(r),.35);const eta=g.courierETA(r);assert.ok(Number.isFinite(eta));assert.ok(eta>d.pickupReadyAt-g.elapsed);});
