const nodes = [
  {id:'charl_west',name:'Bismarckstraße / Kaiser-Friedrich-Straße',districtId:'charlottenburg',x:120,y:445,kind:'hub'},
  {id:'savigny',name:'Savignyplatz',short:'Savignyplatz',districtId:'charlottenburg',x:205,y:470,kind:'hub'},
  {id:'zoo',name:'Zoologischer Garten',short:'Zoo',glyph:'●',districtId:'charlottenburg',x:275,y:470,kind:'landmark',landmarkId:'zoo'},
  {id:'kudamm',name:'Kurfürstendamm',short:"Ku'damm",glyph:'◆',districtId:'charlottenburg',x:180,y:535,kind:'landmark',landmarkId:'kudamm'},
  {id:'ernst_reuter',name:'Ernst-Reuter-Platz',short:'Ernst-Reuter-Platz',districtId:'charlottenburg',x:305,y:410,kind:'hub'},
  {id:'wittenberg',name:'Wittenbergplatz',short:'Wittenbergplatz',districtId:'charlottenburg',x:360,y:540,kind:'hub'},
  {id:'kleistpark',name:'Kleistpark',short:'Kleistpark',districtId:'schoeneberg',x:430,y:620,kind:'service'},
  {id:'nollendorf',name:'Nollendorfplatz',short:'Nollendorfplatz',districtId:'schoeneberg',x:435,y:555,kind:'hub'},
  {id:'victory',name:'Siegessäule',short:'Siegessäule',glyph:'✦',districtId:'tiergarten',x:490,y:440,kind:'landmark',landmarkId:'victory'},
  {id:'tiergarten_s',name:'Tiergartenstraße / Stauffenbergstraße',districtId:'tiergarten',x:520,y:500,kind:'service'},
  {id:'moabit_w',name:'Alt-Moabit / Beusselstraße',districtId:'moabit',x:420,y:325,kind:'service'},
  {id:'turmstr',name:'Turmstraße',short:'Turmstraße',districtId:'moabit',x:500,y:330,kind:'hub'},
  {id:'hbf',name:'Berlin Hauptbahnhof',short:'Hbf',glyph:'▣',districtId:'moabit',x:610,y:335,kind:'landmark',landmarkId:'hauptbahnhof'},
  {id:'reichstag',name:'Reichstag',short:'Reichstag',glyph:'▥',districtId:'mitte',x:635,y:415,kind:'landmark',landmarkId:'reichstag'},
  {id:'brandenburg',name:'Brandenburger Tor',short:'Brandenburger Tor',glyph:'Π',districtId:'mitte',x:665,y:450,kind:'landmark',landmarkId:'brandenburg'},
  {id:'potsdamer',name:'Potsdamer Platz',short:'Potsdamer Platz',glyph:'◇',districtId:'tiergarten',x:620,y:545,kind:'landmark',landmarkId:'potsdamer'},
  {id:'friedrich_ul',name:'Friedrichstraße / Unter den Linden',short:'Friedrichstraße',districtId:'mitte',x:735,y:445,kind:'service'},
  {id:'friedrich_leipzig',name:'Friedrichstraße / Leipziger Straße',districtId:'mitte',x:745,y:535,kind:'service'},
  {id:'checkpoint',name:'Checkpoint Charlie',short:'Checkpoint Charlie',glyph:'✚',districtId:'kreuzberg',x:750,y:585,kind:'landmark',landmarkId:'checkpoint'},
  {id:'mehringplatz',name:'Mehringplatz',short:'Mehringplatz',districtId:'kreuzberg',x:720,y:635,kind:'service'},
  {id:'mehringdamm',name:'Mehringdamm / Gneisenaustraße',short:'Mehringdamm',districtId:'kreuzberg',x:700,y:690,kind:'hub'},
  {id:'suedstern',name:'Südstern',short:'Südstern',districtId:'kreuzberg',x:760,y:735,kind:'service'},
  {id:'luftbruecke',name:'Platz der Luftbrücke',short:'Luftbrücke',districtId:'tempelhof',x:685,y:790,kind:'hub'},
  {id:'tempelhofer',name:'Tempelhofer Feld',short:'Tempelhofer Feld',glyph:'▱',districtId:'tempelhof',x:690,y:875,kind:'landmark',landmarkId:'tempelhofer'},
  {id:'leopold',name:'Leopoldplatz',short:'Leopoldplatz',districtId:'wedding',x:610,y:205,kind:'hub'},
  {id:'gesundbrunnen',name:'Gesundbrunnen',short:'Gesundbrunnen',districtId:'wedding',x:715,y:155,kind:'hub'},
  {id:'nordbahnhof',name:'Nordbahnhof',short:'Nordbahnhof',districtId:'mitte',x:710,y:300,kind:'service'},
  {id:'rosenthaler',name:'Rosenthaler Platz',short:'Rosenthaler Platz',districtId:'mitte',x:810,y:330,kind:'hub'},
  {id:'naturkunde',name:'Invalidenstraße / Chausseestraße',districtId:'mitte',x:665,y:300,kind:'service'},
  {id:'eberwalder',name:'Eberswalder Straße',short:'Eberswalder Straße',districtId:'prenzlauer',x:850,y:225,kind:'hub'},
  {id:'mauerpark',name:'Mauerpark',short:'Mauerpark',glyph:'♧',districtId:'prenzlauer',x:805,y:205,kind:'landmark',landmarkId:'mauerpark'},
  {id:'senefelder',name:'Senefelderplatz',short:'Senefelderplatz',districtId:'prenzlauer',x:855,y:300,kind:'service'},
  {id:'rosa',name:'Rosa-Luxemburg-Platz',short:'Rosa-Luxemburg-Platz',districtId:'mitte',x:865,y:350,kind:'service'},
  {id:'prenzlauer_n',name:'Danziger Straße / Prenzlauer Allee',districtId:'prenzlauer',x:930,y:240,kind:'service'},
  {id:'prenzlauer_s',name:'Prenzlauer Allee / Torstraße',districtId:'prenzlauer',x:910,y:335,kind:'service'},
  {id:'greifswalder',name:'Danziger Straße / Greifswalder Straße',districtId:'prenzlauer',x:1010,y:260,kind:'service'},
  {id:'alex',name:'Alexanderplatz',short:'Alexanderplatz',glyph:'◎',districtId:'mitte',x:930,y:410,kind:'landmark',landmarkId:'alex'},
  {id:'tv',name:'Fernsehturm',short:'TV Tower',glyph:'▲',districtId:'mitte',x:900,y:392,kind:'landmark',landmarkId:'fernsehturm'},
  {id:'museuminsel',name:'Museumsinsel',short:'Museumsinsel',glyph:'▤',districtId:'mitte',x:825,y:435,kind:'landmark',landmarkId:'museuminsel'},
  {id:'spittelmarkt',name:'Spittelmarkt',short:'Spittelmarkt',districtId:'mitte',x:840,y:540,kind:'service'},
  {id:'moritzplatz',name:'Moritzplatz',short:'Moritzplatz',districtId:'kreuzberg',x:845,y:605,kind:'hub'},
  {id:'kotti',name:'Kottbusser Tor',short:'Kottbusser Tor',districtId:'kreuzberg',x:880,y:650,kind:'hub'},
  {id:'oranienplatz',name:'Oranienplatz',short:'Oranienplatz',districtId:'kreuzberg',x:900,y:600,kind:'service'},
  {id:'goerlitzer',name:'Görlitzer Park',short:'Görli',glyph:'♧',districtId:'kreuzberg',x:980,y:675,kind:'landmark',landmarkId:'goerlitzer'},
  {id:'schlesisches',name:'Schlesisches Tor',short:'Schlesisches Tor',districtId:'kreuzberg',x:1035,y:635,kind:'hub'},
  {id:'oberbaum',name:'Oberbaumbrücke',short:'Oberbaumbrücke',glyph:'⌁',districtId:'friedrichshain',x:1080,y:590,kind:'landmark',landmarkId:'oberbaum'},
  {id:'warschauer',name:'Warschauer Straße',short:'Warschauer Straße',districtId:'friedrichshain',x:1100,y:515,kind:'hub'},
  {id:'frankfurter_tor',name:'Frankfurter Tor',short:'Frankfurter Tor',districtId:'friedrichshain',x:1100,y:420,kind:'hub'},
  {id:'strausberger',name:'Strausberger Platz',short:'Strausberger Platz',districtId:'friedrichshain',x:1005,y:420,kind:'service'},
  {id:'ostbahnhof',name:'Ostbahnhof',short:'Ostbahnhof',districtId:'friedrichshain',x:1030,y:500,kind:'hub'},
  {id:'eastside',name:'East Side Gallery',short:'East Side Gallery',glyph:'▰',districtId:'friedrichshain',x:1070,y:555,kind:'landmark',landmarkId:'eastside'},
  {id:'boxi',name:'Boxhagener Platz',short:'Boxhagener Platz',districtId:'friedrichshain',x:1180,y:485,kind:'hub'},
  {id:'jannowitz',name:'Jannowitzbrücke',short:'Jannowitzbrücke',districtId:'mitte',x:940,y:510,kind:'hub'},
  {id:'heinrich_heine',name:'Heinrich-Heine-Straße',short:'Heinrich-Heine-Straße',districtId:'kreuzberg',x:930,y:570,kind:'service'},
  {id:'hermannplatz',name:'Hermannplatz',short:'Hermannplatz',glyph:'◈',districtId:'neukoelln',x:905,y:785,kind:'landmark',landmarkId:'hermannplatz'},
  {id:'rathaus_nk',name:'Rathaus Neukölln',short:'Rathaus Neukölln',districtId:'neukoelln',x:930,y:835,kind:'hub'},
  {id:'karl_marx_nk',name:'Karl-Marx-Straße / Flughafenstraße',districtId:'neukoelln',x:925,y:755,kind:'service'},
  {id:'sonnenallee',name:'Sonnenallee / Pannierstraße',short:'Sonnenallee',districtId:'neukoelln',x:1000,y:790,kind:'hub'},
  {id:'hermannstr',name:'Hermannstraße / Flughafenstraße',short:'Hermannstraße',districtId:'neukoelln',x:830,y:800,kind:'service'},
  {id:'schoeneberg',name:'Rathaus Schöneberg',short:'Rathaus Schöneberg',districtId:'schoeneberg',x:430,y:720,kind:'hub'},
  {id:'bayerischer',name:'Bayerischer Platz',short:'Bayerischer Platz',districtId:'schoeneberg',x:470,y:665,kind:'service'},
  {id:'hallesch',name:'Hallesches Tor',short:'Hallesches Tor',districtId:'kreuzberg',x:760,y:615,kind:'hub'},
  {id:'gleisdreieck',name:'Gleisdreieck',short:'Gleisdreieck',districtId:'kreuzberg',x:585,y:625,kind:'service'},
  {id:'westhafen',name:'Westhafen',short:'Westhafen',districtId:'moabit',x:510,y:255,kind:'service'},
  {id:'jungfernheide_e',name:'Siemensstraße / Beusselstraße',districtId:'moabit',x:410,y:255,kind:'service'},
  {id:'heidestr',name:'Heidestraße / Invalidenstraße',districtId:'moabit',x:590,y:300,kind:'service'},
  {id:'hackescher',name:'Hackescher Markt',short:'Hackescher Markt',districtId:'mitte',x:840,y:390,kind:'service'},
  {id:'molkenmarkt',name:'Molkenmarkt',short:'Molkenmarkt',districtId:'mitte',x:870,y:475,kind:'service'},
  {id:'ostkreuz',name:'Ostkreuz',short:'Ostkreuz',districtId:'friedrichshain',x:1260,y:500,kind:'hub'},
  {id:'samariter',name:'Samariterstraße',short:'Samariterstraße',districtId:'friedrichshain',x:1180,y:420,kind:'service'},
  {id:'treptower',name:'Treptower Park',short:'Treptower Park',districtId:'neukoelln',x:1160,y:710,kind:'service'},
  {id:'neukoelln_s',name:'S-Bahnhof Neukölln',short:'S Neukölln',districtId:'neukoelln',x:930,y:900,kind:'service'},
  {id:'tempelhof_s',name:'S-Bahnhof Tempelhof',short:'S Tempelhof',districtId:'tempelhof',x:700,y:930,kind:'service'}
];

const streets = [
  {name:'Kurfürstendamm',class:'primary',nodes:['kudamm','savigny','zoo','wittenberg']},
  {name:'Kantstraße',class:'secondary',nodes:['charl_west','savigny','zoo']},
  {name:'Bismarckstraße',class:'primary',nodes:['charl_west','ernst_reuter']},
  {name:'Hardenbergstraße',class:'secondary',nodes:['ernst_reuter','zoo']},
  {name:'Straße des 17. Juni',class:'arterial',nodes:['ernst_reuter','victory','brandenburg']},
  {name:'Tiergartenstraße',class:'secondary',nodes:['zoo','victory','tiergarten_s','potsdamer']},
  {name:'Potsdamer Straße',class:'primary',nodes:['potsdamer','nollendorf','kleistpark','schoeneberg']},
  {name:'Alt-Moabit / Turmstraße',class:'primary',nodes:['moabit_w','turmstr','hbf']},
  {name:'Beusselstraße',class:'secondary',nodes:['jungfernheide_e','moabit_w','westhafen']},
  {name:'Invalidenstraße',class:'primary',nodes:['westhafen','heidestr','hbf','naturkunde','nordbahnhof']},
  {name:'Müllerstraße',class:'primary',nodes:['westhafen','leopold','gesundbrunnen']},
  {name:'Brunnenstraße',class:'primary',nodes:['gesundbrunnen','nordbahnhof','rosenthaler']},
  {name:'Schönhauser Allee',class:'primary',nodes:['eberwalder','senefelder','rosa']},
  {name:'Eberswalder / Danziger Straße',class:'primary',nodes:['mauerpark','eberwalder','prenzlauer_n','greifswalder']},
  {name:'Prenzlauer Allee',class:'primary',nodes:['prenzlauer_n','prenzlauer_s','alex']},
  {name:'Torstraße',class:'primary',nodes:['rosenthaler','rosa','prenzlauer_s']},
  {name:'Unter den Linden',class:'arterial',nodes:['brandenburg','friedrich_ul','museuminsel']},
  {name:'Karl-Liebknecht-Straße',class:'primary',nodes:['museuminsel','hackescher','tv','alex']},
  {name:'Friedrichstraße',class:'arterial',nodes:['naturkunde','friedrich_ul','friedrich_leipzig','checkpoint','hallesch','mehringplatz']},
  {name:'Leipziger Straße',class:'primary',nodes:['potsdamer','friedrich_leipzig','spittelmarkt','molkenmarkt']},
  {name:'Alexanderstraße',class:'primary',nodes:['alex','jannowitz']},
  {name:'Karl-Marx-Allee',class:'arterial',nodes:['alex','strausberger','frankfurter_tor','samariter']},
  {name:'Frankfurter Allee',class:'primary',nodes:['frankfurter_tor','samariter','ostkreuz']},
  {name:'Warschauer Straße',class:'primary',nodes:['frankfurter_tor','warschauer','oberbaum']},
  {name:'Mühlenstraße / Stralauer Allee',class:'secondary',nodes:['jannowitz','ostbahnhof','eastside','warschauer']},
  {name:'Boxhagener Straße',class:'secondary',nodes:['frankfurter_tor','boxi','ostkreuz']},
  {name:'Heinrich-Heine-Straße',class:'primary',nodes:['jannowitz','heinrich_heine','moritzplatz']},
  {name:'Oranienstraße',class:'secondary',nodes:['checkpoint','moritzplatz','oranienplatz','kotti']},
  {name:'Gitschiner / Skalitzer Straße',class:'primary',nodes:['hallesch','mehringdamm','kotti','goerlitzer','schlesisches','oberbaum']},
  {name:'Mehringdamm',class:'primary',nodes:['mehringplatz','mehringdamm','suedstern','luftbruecke']},
  {name:'Kottbusser Damm',class:'primary',nodes:['kotti','hermannplatz']},
  {name:'Karl-Marx-Straße',class:'primary',nodes:['hermannplatz','karl_marx_nk','rathaus_nk','neukoelln_s']},
  {name:'Hermannstraße',class:'primary',nodes:['hermannplatz','hermannstr','neukoelln_s']},
  {name:'Sonnenallee',class:'primary',nodes:['hermannplatz','sonnenallee','treptower']},
  {name:'Tempelhofer Damm',class:'primary',nodes:['suedstern','luftbruecke','tempelhofer','tempelhof_s']},
  {name:'Gneisenaustraße',class:'secondary',nodes:['kleistpark','gleisdreieck','mehringdamm','suedstern']},
  {name:'Yorckstraße',class:'secondary',nodes:['nollendorf','gleisdreieck','hallesch']},
  {name:'Grunewaldstraße',class:'secondary',nodes:['nollendorf','bayerischer','schoeneberg']},
  {name:'Urbanstraße',class:'secondary',nodes:['mehringdamm','suedstern','hermannplatz']},
  {name:'Oberbaumbrücke',class:'bridge',nodes:['schlesisches','oberbaum','warschauer']},
  {name:'Moltkebrücke',class:'bridge',nodes:['hbf','reichstag']},
  {name:'Jannowitzbrücke',class:'bridge',nodes:['jannowitz','heinrich_heine']},
  {name:'Spreebogen',class:'secondary',nodes:['hbf','reichstag','brandenburg']},
  {name:'Alexanderufer',class:'secondary',nodes:['hbf','heidestr','naturkunde']},
  {name:'Köpenicker Straße',class:'secondary',nodes:['heinrich_heine','moritzplatz','schlesisches']},
  {name:'Petersburger Straße',class:'secondary',nodes:['greifswalder','frankfurter_tor','warschauer']}
];

export const BERLIN = {
  name:'Berlin', width:1400, height:1000,
  river:[[350,370],[470,360],[580,370],[650,390],[740,420],[820,440],[900,465],[960,500],[1030,535],[1110,555],[1210,560],[1350,585]],
  canal:[[470,610],[560,625],[650,640],[760,650],[860,675],[960,690],[1080,660],[1180,650]],
  parks:[
    {id:'tiergarten',name:'Tiergarten',color:'#77aa72',polygon:[[335,380],[560,365],[635,430],[610,535],[445,555],[330,490]]},
    {id:'tempelhofer-feld',name:'Tempelhofer Feld',color:'#7eaa68',polygon:[[585,805],[805,800],[825,950],[650,980],[555,915]]},
    {id:'goerlitzer-park',name:'Görlitzer Park',color:'#74a56e',polygon:[[930,650],[1010,645],[1025,720],[945,735]]}
  ],
  districts:[
    {id:'charlottenburg',name:'Charlottenburg',color:'#d7a23a',polygon:[[45,330],[330,330],[390,555],[300,640],[60,600]],center:[190,455]},
    {id:'moabit',name:'Moabit',color:'#5aa6c8',polygon:[[330,210],[650,220],[690,390],[520,420],[340,365]],center:[505,300]},
    {id:'wedding',name:'Wedding',color:'#9377c5',polygon:[[500,65],[800,70],[850,255],[650,285],[500,220]],center:[650,165]},
    {id:'prenzlauer',name:'Prenzlauer Berg',color:'#ca7182',polygon:[[790,90],[1090,110],[1100,345],[890,390],[790,270]],center:[940,225]},
    {id:'tiergarten',name:'Tiergarten',color:'#5d9874',polygon:[[315,350],[650,340],[690,570],[430,600],[300,500]],center:[485,470]},
    {id:'mitte',name:'Mitte',color:'#4ca7b8',polygon:[[620,260],[1010,270],[1015,555],[780,620],[620,520]],center:[810,430]},
    {id:'friedrichshain',name:'Friedrichshain',color:'#c2709d',polygon:[[980,300],[1360,320],[1380,610],[1120,675],[1010,560]],center:[1190,460]},
    {id:'kreuzberg',name:'Kreuzberg',color:'#cb854d',polygon:[[560,555],[1080,545],[1120,760],[850,815],[575,735]],center:[820,665]},
    {id:'schoeneberg',name:'Schöneberg',color:'#638fb8',polygon:[[300,555],[600,550],[620,790],[420,825],[260,700]],center:[430,690]},
    {id:'tempelhof',name:'Tempelhof',color:'#7e9f55',polygon:[[520,735],[850,725],[880,995],[560,995]],center:[690,865]},
    {id:'neukoelln',name:'Neukölln',color:'#5a9a68',polygon:[[820,700],[1170,650],[1260,960],[870,995]],center:[1000,825]}
  ],
  nodes, streets,
  landmarks:nodes.filter((node)=>node.kind==='landmark'),
  hubs:nodes.filter((node)=>node.kind==='hub'),
  bridges:[
    {id:'moltkebruecke',name:'Moltkebrücke',short:'Moltkebrücke',edge:['hbf','reichstag']},
    {id:'jannowitzbruecke',name:'Jannowitzbrücke',short:'Jannowitzbrücke',edge:['jannowitz','heinrich_heine']},
    {id:'oberbaumbruecke',name:'Oberbaumbrücke',short:'Oberbaumbrücke',edge:['schlesisches','oberbaum']}
  ]
};

export function districtById(id){ return BERLIN.districts.find((district)=>district.id===id); }
export function landmarkById(id){ return BERLIN.landmarks.find((landmark)=>landmark.landmarkId===id||landmark.id===id); }
export function bridgeById(id){ return BERLIN.bridges.find((bridge)=>bridge.id===id); }
