import { Game } from './game-core.js';
import { RADIO_CHANNELS } from './game-data.js';

function personalityBonus(c,{closeness,urgency,reward,critical,same,longRide}){
  switch(c.personality.id){
    case'sprinter':return(closeness>.62?.38:0)+(urgency>.38?.5:0)+(closeness>.62&&urgency>.38?.32:0);
    case'earner':return reward>.95?.62:reward<.55?-.08:0;
    case'guardian':return critical?.52:urgency>.52?.24:0;
    case'local':return(same?.42:0)+(closeness>.72?.18:0);
    case'tourer':return longRide>.62?.56:longRide>.45?.2:0;
    case'steady':return closeness>.3&&closeness<.82&&reward>.4&&reward<1.15&&urgency>.12&&urgency<.72?.32:0;
    default:return 0;
  }
}

Object.assign(Game.prototype,{
  setChannel(deliveryId,channelId){const d=this.deliveryById(deliveryId);if(!d||d.status!=='waiting')return false;if(channelId===null||channelId==='off'){if(!d.called)return true;const previous=d.channel;d.called=false;d.channel=null;d.callHistory.push({at:this.elapsed,channel:null});this.invalidateDeliberations(d.id);this.logDispatch('uncall',d,{channel:previous});this.flash(`OFF RADIO · ${d.id.toUpperCase()} held back`,3);return true;}const channel=RADIO_CHANNELS[channelId];if(!channel)return false;const nextUsed=this.radioUsed()-this.radioCost(d)+channel.cost;if(nextUsed>this.radioSlots){this.runStats.radioDenied+=1;this.logDispatch('radio-denied',d,{channel:channelId});this.flash(`RADIO FULL · ${channel.short} needs ${channel.cost}`,3);return false;}const wasCalled=d.called,previous=d.channel;d.called=true;d.channel=channelId;d.firstCalledAt??=this.elapsed;d.callHistory.push({at:this.elapsed,channel:channelId});this.selectedDeliveryId=d.id;this.runStats.peakRadio=Math.max(this.runStats.peakRadio,this.radioUsed());this.logDispatch(wasCalled?'channel':'call',d,{channel:channelId,previous});if(previous&&previous!==channelId)this.invalidateDeliberations(d.id);for(const c of this.availableRiders())c.decisionAt=Math.min(c.decisionAt,this.elapsed+.16);this.flash(`${channel.short} · ${d.id.toUpperCase()} · ${d.pickupAddress}`,3);return true;},
  toggleCall(id){const d=this.deliveryById(id);return d?.called?this.setChannel(id,'off'):this.setChannel(id,'open');},
  invalidateDeliberations(id){for(const c of this.couriers)if(c.deliberation?.deliveryId===id){c.deliberation=null;c.decisionAt=this.elapsed+.1;}},
  selectDelivery(id){this.selectedDeliveryId=this.selectedDeliveryId===id?null:id;},
  selectCourier(id){this.selectedCourierId=this.selectedCourierId===id?null:id;},
  courierChoiceScore(c,d,withNoise=true){if(!c?.radioOn||c.phase!=='idle')return-Infinity;const pickup=this.nodeById(d.pickupId),current=this.nodeById(c.nodeId),travel=Math.max(1,this.routeTravelCost(c.nodeId,pickup.id)),closeness=1/(1+travel/190),urgency=1-this.urgency(d),reward=Math.min(1.9,d.reward/30),critical=d.type==='medical'||d.type==='coldchain'?1:0,same=current?.districtId===pickup?.districtId?1:0,longRide=Math.min(1,d.plannedDistance/900),w=c.personality.weights,features={closeness,urgency,reward,critical,same,longRide};let score=closeness*(w.distance??0)+urgency*(w.urgency??0)+reward*(w.reward??0)+critical*(w.medical??0)+same*(w.sameDistrict??0)+longRide*(w.longRide??0)+personalityBonus(c,features);if(d.channel==='priority')score+=RADIO_CHANNELS.priority.appeal;if(d.channel==='local')score+=same?.74:closeness>.6?.24:-.28;score+=(d.bonusAppeal??0);if((d.rebroadcastUntil??0)>this.elapsed)score+=.22;score-=c.fatigue*.27;if(withNoise)score+=this.rng.float(-c.experience.noise/this.modifiers.teamSkill,c.experience.noise/this.modifiers.teamSkill);return score;},
  predictCall(c){if(!c||c.phase!=='idle'||!c.radioOn)return null;if(c.deliberation){const d=this.deliveryById(c.deliberation.deliveryId);if(d?.called&&d.status==='waiting')return{delivery:d,score:c.deliberation.score,deliberating:true};}const calls=this.calledDeliveries();if(!calls.length)return null;return calls.map(d=>({delivery:d,score:this.courierChoiceScore(c,d,false)})).sort((a,b)=>b.score-a.score)[0]??null;},
  beginDeliberation(c){if(!c.radioOn||c.phase!=='idle')return false;const calls=this.calledDeliveries();if(!calls.length){c.lastDecision='Listening · no live calls';c.decisionAt=this.elapsed+this.decisionDelay(c);return false;}const ranked=calls.map(d=>({delivery:d,score:this.courierChoiceScore(c,d,true)})).sort((a,b)=>b.score-a.score),best=ranked[0];if(!best||best.score<.3){c.lastDecision='Waiting for a better fit';c.decisionAt=this.elapsed+this.decisionDelay(c);return false;}const duration=Math.max(.3,c.experience.think/this.modifiers.teamSkill*this.rng.float(.5,.84));c.deliberation={deliveryId:best.delivery.id,startedAt:this.elapsed,readyAt:this.elapsed+duration,score:best.score,reason:this.choiceReason(c,best.delivery)};c.lastDecision=`Considering ${best.delivery.id.toUpperCase()} · ${c.deliberation.reason}`;return true;},
  deliberationProgress(c){if(!c?.deliberation)return 0;const total=Math.max(.001,c.deliberation.readyAt-c.deliberation.startedAt);return Math.max(0,Math.min(1,(this.elapsed-c.deliberation.startedAt)/total));},
  resolveDeliberation(c){const thought=c.deliberation;if(!thought)return false;const d=this.deliveryById(thought.deliveryId);c.deliberation=null;if(!d||d.status!=='waiting'||!d.called||!c.radioOn){c.decisionAt=this.elapsed+.14;return false;}return this.claim(c,d,thought.score);},
  claim(c,d,score=0){if(!c?.radioOn||c.phase!=='idle'||!d?.called||d.status!=='waiting')return false;const path=this.routeBetween(c.nodeId,d.pickupId);if(!path.length)return false;d.status='claimed';d.called=false;d.claimedAt=this.elapsed;d.courierId=c.id;d.pickupLegDistance=this.routeDistance(path);c.deliveryId=d.id;c.phase='pickup';c.deliberation=null;this.setCourierPath(c,path,d.pickupId);c.lastDecision=`Took ${d.id.toUpperCase()} · ${this.choiceReason(c,d)}`;this.runStats.riderChoices+=1;this.logDispatch('claim',d,{rider:c.name,score});this.invalidateDeliberations(d.id);this.flash(`${c.name} chose ${d.id.toUpperCase()} · ${d.pickupAddress}`,3);return true;},
  choiceReason(c,d){const pickup=this.nodeById(d.pickupId),current=this.nodeById(c.nodeId);if((d.rebroadcastUntil??0)>this.elapsed)return'rebroadcast';if((d.bonusAppeal??0)>.2)return'added bonus';if(d.channel==='priority')return'priority signal';if(d.channel==='local'&&current?.districtId===pickup?.districtId)return'local pickup';if((d.type==='medical'||d.type==='coldchain')&&c.personality.id==='guardian')return'critical cargo';if(this.urgency(d)<.32)return'urgent';if(c.personality.id==='earner'&&d.reward>=28)return`€${d.reward}`;if(c.personality.id==='tourer'&&d.plannedDistance>580)return'long ride';if(this.routeTravelCost(c.nodeId,d.pickupId)<155)return'close pickup';return c.personality.title.toLowerCase();}
});
