import { BERLIN } from './berlin.js';
import { Game } from './game-core.js';
import { COURIER_NAMES,ROAD_EVENT_TYPES,UPGRADES } from './game-data.js';

Object.assign(Game.prototype,{
  scheduleRoadEvent(){const template=this.rng.pick(ROAD_EVENT_TYPES);let graphEdges=[],visualIds=[],place='Berlin';if(template.bridgeOnly){const bridges=BERLIN.bridges.filter(bridge=>this.visualEdges.some(v=>v.bridgeId===bridge.id&&this.visualEdgePlayable(v.id)));const bridge=this.rng.pick(bridges);if(bridge){visualIds=this.visualEdges.filter(v=>v.bridgeId===bridge.id&&this.visualEdgePlayable(v.id)).map(v=>v.id);graphEdges=this.edges.filter(e=>visualIds.includes(e.visualId)&&this.edgePlayable(e));place=bridge.short;}}if(!graphEdges.length){const candidates=this.visualEdges.filter(e=>e.roadClass!=='connector'&&!e.bikeLane&&this.visualEdgePlayable(e.id));const selected=this.rng.shuffle(candidates).slice(0,this.rng.chance(.3)?2:1);visualIds=selected.map(e=>e.id);graphEdges=this.edges.filter(e=>visualIds.includes(e.visualId)&&this.edgePlayable(e));place=selected[0]?.streetName??'Berlin';}if(!graphEdges.length){this.nextEventAt=this.elapsed+35;return;}const startsAt=this.nextEventAt,duration=this.rng.float(...template.duration);this.currentEvent={id:`event-${Math.round(startsAt)}`,type:template.id,title:template.title,detail:template.forecast,place,state:'forecast',startsAt,endsAt:startsAt+duration,factor:template.factor,edgeIds:graphEdges.map(e=>e.id),visualIds,advisory:false};this.logDispatch('event-forecast',null,{title:template.title,place});this.flash(`${template.title} forecast · ${place}`,5);},
  updateRoadEvent(){if(!this.currentEvent&&this.elapsed>=this.nextEventAt-10)this.scheduleRoadEvent();const ev=this.currentEvent;if(!ev)return;if(ev.state==='forecast'&&this.elapsed>=ev.startsAt){ev.state='active';for(const e of this.edges)if(ev.edgeIds.includes(e.id))e.eventMultiplier=ev.factor;for(const c of this.couriers)if(c.phase==='pickup'||c.phase==='dropoff')this.rerouteCourier(c);this.logDispatch('event-start',null,{title:ev.title,place:ev.place});this.flash(`${ev.title} ACTIVE · ${ev.place}`,5);}if(ev.state==='active'&&this.elapsed>=ev.endsAt){for(const e of this.edges)if(ev.edgeIds.includes(e.id))e.eventMultiplier=1;this.logDispatch('event-end',null,{title:ev.title,place:ev.place});this.currentEvent=null;this.nextEventAt=this.elapsed+50+this.rng.float(0,34);}},
  generateGoals(){const unlockedVisual=this.visualEdges.filter(e=>e.roadClass!=='connector'&&this.visualEdgePlayable(e.id)),street=this.rng.pick([...new Set(unlockedVisual.map(e=>e.streetName))]),district=this.rng.pick(this.districts.filter(d=>(d.unlockLevel??1)<=this.cityLevel));return[
    {id:'street',type:'street',targetId:street,label:`Work ${street}`,detail:`4 jobs touch ${street}.`,progress:0,target:4,reward:18,complete:false},
    {id:'district',type:'district',targetId:district.id,label:`Cover ${district.name}`,detail:`6 jobs touch this area.`,progress:0,target:6,reward:20,complete:false},
    {id:'reliability',type:'reliability',label:'Reliable radio',detail:'Complete 12 deliveries.',progress:0,target:12,reward:24,complete:false}
  ];},
  addExpansionGoals(){if(this.cityLevel>=2&&!this.goals.some(g=>g.type==='bridge')){const bridges=BERLIN.bridges.filter(bridge=>this.visualEdges.some(v=>v.bridgeId===bridge.id&&this.visualEdgePlayable(v.id))),bridge=this.rng.pick(bridges);if(bridge)this.goals.push({id:'bridge',type:'bridge',targetId:bridge.id,label:`Cross ${bridge.short}`,detail:'3 completed routes use this bridge.',progress:0,target:3,reward:24,complete:false});}if(this.cityLevel>=3&&!this.goals.some(g=>g.type==='cross'))this.goals.push({id:'cross',type:'cross',label:'Cross the Ring desk',detail:'Complete 8 cross-area deliveries.',progress:0,target:8,reward:30,complete:false});},
  updateGoals(d){for(const g of this.goals){if(g.complete)continue;const p=this.nodeById(d.pickupId),q=this.nodeById(d.dropoffId),bridges=new Set(d.edgesTraversed.map(id=>this.edges.find(e=>e.id===id)?.bridgeId).filter(Boolean));let hit=false;if(g.type==='street')hit=p?.streetName===g.targetId||q?.streetName===g.targetId;if(g.type==='district')hit=p?.districtId===g.targetId||q?.districtId===g.targetId;if(g.type==='bridge')hit=bridges.has(g.targetId);if(g.type==='reliability')hit=true;if(g.type==='cross')hit=p?.districtId&&q?.districtId&&p.districtId!==q.districtId;if(!hit)continue;g.progress+=1;if(g.progress>=g.target){g.complete=true;this.cash+=g.reward;this.score+=g.reward*20;this.reputation=Math.min(100,this.reputation+7);this.logDispatch('goal',d,{goal:g.label});this.flash(`GOAL · ${g.label} · +€${g.reward}`,5);}}},
  getUpgradeChoices(){return this.rng.shuffle(UPGRADES.filter(u=>u.id!=='rider'||this.courierSerial<COURIER_NAMES.length)).slice(0,3);},
  applyUpgrade(id){const u=UPGRADES.find(x=>x.id===id);if(!u||!this.upgradePending)return false;u.apply(this);this.upgradePending=false;this.nextUpgradeAt+=8+Math.floor(this.nextUpgradeAt/16);this.logDispatch('upgrade',null,{upgrade:u.title});this.flash(`${u.title} added`,4);return true;},
  deliveryLabel(d){return `${d.pickupAddress} → ${d.dropoffAddress}`;},
  nearestIdleDistance(d){const riders=this.availableRiders();if(!riders.length)return null;return Math.min(...riders.map(c=>this.routeTravelCost(c.nodeId,d.pickupId)));},
  flash(message,duration=4){this.notice=message;this.noticeUntil=this.elapsed+duration;},
  logDispatch(action,delivery=null,extra={}){this.dispatchLog.push({at:this.elapsed,action,deliveryId:delivery?.id??null,pickup:delivery?.pickupAddress??null,dropoff:delivery?.dropoffAddress??null,radioUsed:this.radioUsed(),cityLevel:this.cityLevel,...extra});if(this.dispatchLog.length>260)this.dispatchLog.splice(0,this.dispatchLog.length-260);},
  nearestEntity(x,y,maxDistance=28){let best=null;for(const d of this.activeDeliveries()){const n=this.nodeById(d.pickedUp?d.dropoffId:d.pickupId),dd=Math.hypot(n.x-x,n.y-y);if(dd<=maxDistance&&(!best||dd<best.distance))best={type:'delivery',id:d.id,distance:dd};}for(const c of this.couriers){const dd=Math.hypot(c.x-x,c.y-y);if(dd<=maxDistance&&(!best||dd<best.distance))best={type:'courier',id:c.id,distance:dd};}return best;},
  dispatchReview(){const done=this.deliveries.filter(d=>['completed','failed'].includes(d.status)),fail=done.filter(d=>d.status==='failed'),never=fail.filter(d=>d.failureKind==='never-called').length,unclaimed=fail.filter(d=>d.failureKind==='called-unclaimed').length,late=fail.filter(d=>d.failureKind==='claimed-late').length,top=[...this.couriers].sort((a,b)=>b.completed-a.completed)[0],advice=[];if(never>=2)advice.push(`${never} jobs expired before broadcast. Hold less low-risk work.`);if(unclaimed>=2)advice.push(`${unclaimed} broadcasts had no taker. Match channel, payout and rider position.`);if(late>=2)advice.push(`${late} accepted jobs still arrived late. Client calls or bonuses may have been cheaper.`);if(this.runStats.radioDenied>=2)advice.push(`Bandwidth blocked ${this.runStats.radioDenied} radio changes. Keep one slot flexible.`);if(this.runStats.breaks>=2)advice.push(`${this.runStats.breaks} breaks reduced coverage. Read energy before opening distant calls.`);if(this.runStats.toolsUsed===0&&this.completed>=8)advice.push('You never used dispatch tools. Bonuses, client calls and advisories can reshape a bad desk.');if(!advice.length)advice.push('The desk stayed disciplined. Improve timing around events and rider energy.');return{neverCalled:never,calledUnclaimed:unclaimed,claimedLate:late,radioDenied:this.runStats.radioDenied,breaks:this.runStats.breaks,toolsUsed:this.runStats.toolsUsed,stage:this.currentStage().name,topRider:top?`${top.name} · ${top.completed} deliveries`:'—',advice};},
  summary(){return{score:Math.round(this.score),completed:this.completed,failed:this.failed,wave:this.wave,distanceKm:(this.runStats.distance/100).toFixed(1),seed:this.seed,goals:this.goals.filter(g=>g.complete).length,riderChoices:this.runStats.riderChoices,cityLevel:this.cityLevel,review:this.dispatchReview()};}
});
