import { RNG, createSeed } from './rng.js';
import { buildAdjacency, distance, shortestPath } from './graph.js';
import { BERLIN } from './berlin.js';
import { buildDetailedBerlin } from './berlin-detail.js';
import { COURIER_COLORS,COURIER_NAMES,DELIVERY_TYPES,EXPERIENCE,PERSONALITIES,RADIO_CHANNELS,RUN_TRAITS,edgeKey,weightedPick } from './game-data.js';
export class Game{
constructor({seed=createSeed(),width=BERLIN.width,height=BERLIN.height}={}){this.seed=seed;this.rng=new RNG(seed);this.width=width;this.height=height;this.elapsed=0;this.score=0;this.cash=0;this.reputation=100;this.completed=0;this.failed=0;this.wave=1;this.speed=1;this.paused=false;this.gameOver=false;this.upgradePending=false;this.nextUpgradeAt=8;this.deliverySerial=0;this.courierSerial=0;this.spawnAccumulator=0;this.selectedDeliveryId=null;this.selectedCourierId=null;this.radioSlots=4;this.notice='Broadcast jobs. Riders choose for themselves.';this.noticeUntil=9;this.modifiers={speed:1,deadline:1,reward:1,teamSkill:1,landmarkBias:.18};this.runStats={peakActive:0,peakRadio:0,distance:0,riderChoices:0,radioDenied:0,eventExposure:0,breaks:0};this.dispatchLog=[];this.generateBerlin();this.deliveries=[];this.couriers=[];this.runTrait=this.rng.pick(RUN_TRAITS);this.runTrait.apply(this);for(let i=0;i<3;i+=1)this.addCourier();this.goals=this.generateGoals();this.currentEvent=null;this.nextEventAt=52+this.rng.float(0,20);for(let i=0;i<5;i+=1)this.spawnDelivery();}
generateBerlin(){this.districts=BERLIN.districts.map((d)=>({...d,polygon:d.polygon.map((p)=>[...p])}));this.parks=BERLIN.parks.map((p)=>({...p,polygon:p.polygon.map((q)=>[...q])}));this.river=BERLIN.river.map((p)=>[...p]);this.canal=BERLIN.canal.map((p)=>[...p]);this.landmarks=BERLIN.landmarks.map((l)=>({...l}));const detail=buildDetailedBerlin();this.nodes=detail.nodes;this.streetDefinitions=detail.streets;this.gridNodeCount=detail.gridNodeCount;this.edges=[];const byId=new Map(this.nodes.map((n)=>[n.id,n])),seen=new Map(),bridgeMap=new Map(BERLIN.bridges.map((b)=>[edgeKey(...b.edge),b.id])),classSpeed={arterial:1.02,primary:1,secondary:.97,local:.94,bridge:.98,connector:.92};for(const street of this.streetDefinitions)for(let i=1;i<street.nodes.length;i+=1){const aId=street.nodes[i-1],bId=street.nodes[i],a=byId.get(aId),b=byId.get(bId);if(!a||!b)continue;const key=edgeKey(aId,bId);if(seen.has(key)){const e=seen.get(key);if(!e.streetNames.includes(street.name))e.streetNames.push(street.name);if(street.class==='arterial')e.roadClass='arterial';continue;}const e={id:`e${this.edges.length}`,a:aId,b:bId,distance:distance(a,b),speed:classSpeed[street.class]??.94,bikeLane:false,eventMultiplier:1,roadClass:street.class,streetName:street.name,streetNames:[street.name],bridgeId:bridgeMap.get(key)??null};this.edges.push(e);seen.set(key,e);}this.ensureConnectivity();this.depotNodeId='checkpoint';}
ensureConnectivity(){const components=()=>{const adjacency=buildAdjacency(this.nodes,this.edges),remaining=new Set(this.nodes.map((n)=>n.id)),groups=[];while(remaining.size){const first=remaining.values().next().value,stack=[first],group=[];remaining.delete(first);while(stack.length){const id=stack.pop();group.push(id);for(const{to}of adjacency.get(id)??[])if(remaining.has(to)){remaining.delete(to);stack.push(to);}}groups.push(group);}return groups;};let groups=components();while(groups.length>1){const main=groups[0].map((id)=>this.nodeById(id));let best=null;for(let gi=1;gi<groups.length;gi+=1)for(const a of main)for(const id of groups[gi]){const b=this.nodeById(id),d=distance(a,b);if(!best||d<best.d)best={a,b,d};}this.edges.push({id:`e${this.edges.length}`,a:best.a.id,b:best.b.id,distance:best.d,speed:.9,bikeLane:false,eventMultiplier:1,roadClass:'connector',streetName:'local connection',streetNames:['local connection'],bridgeId:null});groups=components();}}
promoteBikeLanes(count,speed=1.4){for(const e of this.rng.shuffle(this.edges.filter((x)=>x.roadClass!=='connector'&&x.roadClass!=='local')).slice(0,count)){e.speed=Math.max(e.speed,speed);e.bikeLane=true;}}
nodeById(id){return this.nodes.find((n)=>n.id===id);}deliveryById(id){return this.deliveries.find((d)=>d.id===id);}courierById(id){return this.couriers.find((c)=>c.id===id);}edgeByIds(a,b){return this.edges.find((e)=>edgeKey(e.a,e.b)===edgeKey(a,b));}
addCourier(){if(this.courierSerial>=COURIER_NAMES.length)return false;const depot=this.nodeById(this.depotNodeId),index=this.courierSerial++,personality=this.rng.pick(PERSONALITIES),experience=weightedPick(this.rng,EXPERIENCE,(e)=>[0,3.1,4.1,2.8,1.2][e.level]),homeDistrict=this.rng.pick(this.districts).id;this.couriers.push({id:`c${index}`,name:COURIER_NAMES[index],color:COURIER_COLORS[index],personality,experience,homeDistrict,nodeId:depot.id,x:depot.x+(index-1)*9,y:depot.y+(index-1)*7,path:[],pathIndex:0,targetNodeId:null,deliveryId:null,phase:'idle',baseSpeed:62+this.rng.float(-3,5),decisionAt:this.elapsed+this.rng.float(.35,1.2),deliberation:null,lastDecision:'Radio on · listening.',completed:0,radioOn:true,fatigue:this.rng.float(.04,.14),breakUntil:null,breaks:0});return true;}
incidentStreetNames(nodeId){const names=[];for(const edge of this.edges)if(edge.a===nodeId||edge.b===nodeId)for(const name of edge.streetNames??[edge.streetName])if(name&&!name.includes('access')&&!name.includes('connection')&&!names.includes(name))names.push(name);return names;}
addressForNode(node){const hints=node.addresses?.filter((a)=>a.street);if(hints?.length){const hint=this.rng.pick(hints),number=Math.max(1,hint.number+this.rng.int(0,4)*2);return{nodeId:node.id,street:hint.street,number,label:`${hint.street} ${number}`,districtId:node.districtId};}const streets=this.incidentStreetNames(node.id),street=this.rng.pick(streets)??node.short??node.name??'Berlin';const raw=1+((Math.round(node.x*.31+node.y*.17)+this.rng.int(0,70))%188),number=this.rng.chance(.5)?raw|1:raw+(raw%2);return{nodeId:node.id,street,number,label:`${street} ${Math.max(1,number)}`,districtId:node.districtId,landmark:node.landmarkId??null};}
randomEndpoint(excludeId=null,origin=null){const all=this.nodes.filter((n)=>n.id!==excludeId&&n.id!==this.depotNodeId&&n.roadClass!=='connector');const goal=this.goals?.find((g)=>g.type==='landmark'&&!g.complete);if(goal&&this.rng.chance(.1)){const target=all.find((n)=>n.landmarkId===goal.targetId);if(target)return target;}let pool=all;if(origin){const spaced=pool.filter((n)=>distance(origin,n)>95);if(spaced.length)pool=spaced;}const addressNodes=pool.filter((n)=>n.kind==='address');if(addressNodes.length&&this.rng.chance(.86))pool=addressNodes;const districtGoal=this.goals?.find((g)=>g.type==='district'&&!g.complete);if(districtGoal&&this.rng.chance(.09)){const local=pool.filter((n)=>n.districtId===districtGoal.targetId);if(local.length)pool=local;}return this.rng.pick(pool);}
spawnDelivery(){if(this.activeDeliveries().length>=34)return;let pickup=null,dropoff=null,route=[];for(let attempt=0;attempt<8&&!route.length;attempt+=1){pickup=this.randomEndpoint();dropoff=this.randomEndpoint(pickup?.id,pickup);if(!pickup||!dropoff)continue;route=shortestPath(this.nodes,this.edges,pickup.id,dropoff.id,this.edgeCost.bind(this));if(route.length&&this.pathDistance(route)<90)route=[];}if(!route.length)return;const typeKey=this.rng.pick(Object.keys(DELIVERY_TYPES)),type=DELIVERY_TYPES[typeKey],routeDistance=this.pathDistance(route),distanceTier=routeDistance<260?'SHORT':routeDistance<520?'MID':'LONG',deadline=type.baseDeadline*this.modifiers.deadline*(.84+routeDistance/920)/(1+(this.wave-1)*.016),id=`d${this.deliverySerial++}`,pickupAddress=this.addressForNode(pickup),dropoffAddress=this.addressForNode(dropoff);this.deliveries.push({id,type:typeKey,pickupId:pickup.id,dropoffId:dropoff.id,pickupAddress,dropoffAddress,routeDistance,distanceTier,createdAt:this.elapsed,deadlineAt:this.elapsed+deadline,reward:Math.round((type.reward+routeDistance/105)*this.modifiers.reward),status:'waiting',called:false,channel:null,courierId:null,pickedUp:false,firstCalledAt:null,claimedAt:null,edgesTraversed:[],callHistory:[]});this.runStats.peakActive=Math.max(this.runStats.peakActive,this.activeDeliveries().length);}
activeDeliveries(){return this.deliveries.filter((d)=>d.status==='waiting'||d.status==='claimed');}calledDeliveries(){return this.deliveries.filter((d)=>d.status==='waiting'&&d.called);}calledCount(){return this.calledDeliveries().length;}radioCost(d){return d?.called?(RADIO_CHANNELS[d.channel]?.cost??1):0;}radioUsed(){return this.calledDeliveries().reduce((s,d)=>s+this.radioCost(d),0);}availableRiders(){return this.couriers.filter((c)=>c.phase==='idle'&&c.radioOn);}
edgeCost(e){return e.distance/Math.max(.18,e.speed*(e.eventMultiplier??1));}pathDistance(path){let total=0;for(let i=1;i<(path?.length??0);i+=1)total+=this.edgeByIds(path[i-1],path[i])?.distance??0;return total;}urgency(d){const total=Math.max(1,d.deadlineAt-d.createdAt);return Math.max(0,Math.min(1,(d.deadlineAt-this.elapsed)/total));}
}
