import { BERLIN } from './berlin.js';
import { Game } from './game-core.js';
import { COURIER_NAMES,ROAD_EVENT_TYPES,UPGRADES } from './game-data.js';
Object.assign(Game.prototype,{
scheduleRoadEvent(){const template=this.rng.pick(ROAD_EVENT_TYPES);let graphEdges=[],visualIds=[],place='central Berlin';if(template.bridgeOnly){const bridge=this.rng.pick(BERLIN.bridges);graphEdges=this.edges.filter((e)=>e.bridgeId===bridge.id);visualIds=[...new Set(graphEdges.map((e)=>e.visualId))];place=bridge.short;}if(!graphEdges.length){const candidates=this.visualEdges.filter((e)=>{const a=this.nodeById(e.a),b=this.nodeById(e.b),mx=(a.x+b.x)/2,my=(a.y+b.y)/2;return mx>430&&mx<1080&&my>180&&my<700&&e.roadClass!=='connector'&&!e.bikeLane;});const selected=this.rng.shuffle(candidates).slice(0,this.rng.chance(.3)?2:1);visualIds=selected.map((e)=>e.id);graphEdges=this.edges.filter((e)=>visualIds.includes(e.visualId));place=selected[0]?.streetName??'central Berlin';}const startsAt=this.nextEventAt,duration=this.rng.float(...template.duration);this.currentEvent={id:`event-${Math.round(startsAt)}`,type:template.id,title:template.title,detail:template.forecast,place,state:'forecast',startsAt,endsAt:startsAt+duration,factor:template.factor,edgeIds:graphEdges.map((e)=>e.id),visualIds};this.logDispatch('event-forecast',null,{title:template.title,place});this.flash(`${template.title} forecast · ${place}`,5);},
updateRoadEvent(){if(!this.currentEvent&&this.elapsed>=this.nextEventAt-10)this.scheduleRoadEvent();const ev=this.currentEvent;if(!ev)return;if(ev.state==='forecast'&&this.elapsed>=ev.startsAt){ev.state='active';for(const e of this.edges)if(ev.edgeIds.includes(e.id))e.eventMultiplier=ev.factor;this.logDispatch('event-start',null,{title:ev.title,place:ev.place});this.flash(`${ev.title} ACTIVE · ${ev.place}`,5);}if(ev.state==='active'&&this.elapsed>=ev.endsAt){for(const e of this.edges)if(ev.edgeIds.includes(e.id))e.eventMultiplier=1;this.logDispatch('event-end',null,{title:ev.title,place:ev.place});this.currentEvent=null;this.nextEventAt=this.elapsed+50+this.rng.float(0,34);}},
generateGoals(){const street=this.rng.pick(this.streetCatalog.filter((name)=>!name.includes('brücke'))),district=this.rng.pick(this.districts),bridge=this.rng.pick(BERLIN.bridges);return[
{id:'street',type:'street',targetId:street,label:`Work ${street}`,detail:`Complete 4 jobs starting or ending on ${street}.`,progress:0,target:4,reward:18,complete:false},
{id:'district',type:'district',targetId:district.id,label:`Cover ${district.name}`,detail:`Complete 6 jobs touching ${district.name}.`,progress:0,target:6,reward:20,complete:false},
{id:'bridge',type:'bridge',targetId:bridge.id,label:`Cross ${bridge.short}`,detail:`Complete 3 deliveries whose ridden route uses ${bridge.name}.`,progress:0,target:3,reward:22,complete:false},
{id:'reliability',type:'reliability',label:'Reliable radio',detail:'Complete 12 deliveries.',progress:0,target:12,reward:24,complete:false}
];},
updateGoals(d){for(const g of this.goals){if(g.complete)continue;const p=this.nodeById(d.pickupId),q=this.nodeById(d.dropoffId),bridges=new Set(d.edgesTraversed.map((id)=>this.edges.find((e)=>e.id===id)?.bridgeId).filter(Boolean));let hit=false;if(g.type==='street')hit=p.streetName===g.targetId||q.streetName===g.targetId;if(g.type==='district')hit=p.districtId===g.targetId||q.districtId===g.targetId;if(g.type==='bridge')hit=bridges.has(g.targetId);if(g.type==='reliability')hit=true;if(!hit)continue;g.progress+=1;if(g.progress>=g.target){g.complete=true;this.cash+=g.reward;this.score+=g.reward*20;this.reputation=Math.min(100,this.reputation+7);this.logDispatch('goal',d,{goal:g.label});this.flash(`GOAL · ${g.label} · +€${g.reward}`,5);}}},
getUpgradeChoices(){return this.rng.shuffle(UPGRADES.filter((u)=>u.id!=='rider'||this.courierSerial<COURIER_NAMES.length)).slice(0,3);},
applyUpgrade(id){const u=UPGRADES.find((x)=>x.id===id);if(!u||!this.upgradePending)return false;u.apply(this);this.upgradePending=false;this.nextUpgradeAt+=8+Math.floor(this.nextUpgradeAt/16);this.logDispatch('upgrade',null,{upgrade:u.title});this.flash(`${u.title} added`,4);return true;},
deliveryLabel(d){return `${d.pickupAddress} → ${d.dropoffAddress}`;},
nearestIdleDistance(d){const riders=this.availableRiders();if(!riders.length)return null;return Math.min(...riders.map((c)=>this.routeTravelCost(c.nodeId,d.pickupId)));},
flash(message,duration=4){this.notice=message;this.noticeUntil=this.elapsed+duration;},
logDispatch(action,delivery=null,extra={}){this.dispatchLog.push({at:this.elapsed,action,deliveryId:delivery?.id??null,pickup:delivery?.pickupAddress??null,dropoff:delivery?.dropoffAddress??null,radioUsed:this.radioUsed(),...extra});if(this.dispatchLog.length>220)this.dispatchLog.splice(0,this.dispatchLog.length-220);},
nearestEntity(x,y,maxDistance=28){let best=null;for(const d of this.activeDeliveries()){const n=this.nodeById(d.pickedUp?d.dropoffId:d.pickupId),dd=Math.hypot(n.x-x,n.y-y);if(dd<=maxDistance&&(!best||dd<best.distance))best={type:'delivery',id:d.id,distance:dd};}for(const c of this.couriers){const dd=Math.hypot(c.x-x,c.y-y);if(dd<=maxDistance&&(!best||dd<best.distance))best={type:'courier',id:c.id,distance:dd};}return best;},
dispatchReview(){const done=this.deliveries.filter((d)=>['completed','failed'].includes(d.status)),fail=done.filter((d)=>d.status==='failed'),never=fail.filter((d)=>d.failureKind==='never-called').length,unclaimed=fail.filter((d)=>d.failureKind==='called-unclaimed').length,late=fail.filter((d)=>d.failureKind==='claimed-late').length,top=[...this.couriers].sort((a,b)=>b.completed-a.completed)[0],advice=[];if(never>=2)advice.push(`${never} jobs expired before you broadcast them. Call earlier or ignore low-value work sooner.`);if(unclaimed>=2)advice.push(`${unclaimed} broadcasts had no taker. Match calls to rider position and personality.`);if(late>=2)advice.push(`${late} accepted jobs still arrived late. Avoid long pickups and disrupted streets.`);if(this.runStats.radioDenied>=2)advice.push(`Bandwidth blocked ${this.runStats.radioDenied} radio changes. Keep one slot flexible.`);if(this.runStats.breaks>=2)advice.push(`${this.runStats.breaks} rider breaks reduced coverage. Anticipate fatigue before the rush.`);if(!advice.length)advice.push('The desk stayed disciplined. Improve route timing and use LOCAL/PRIORITY more selectively.');return{neverCalled:never,calledUnclaimed:unclaimed,claimedLate:late,radioDenied:this.runStats.radioDenied,breaks:this.runStats.breaks,topRider:top?`${top.name} · ${top.completed} deliveries`:'—',advice};},
summary(){return{score:Math.round(this.score),completed:this.completed,failed:this.failed,wave:this.wave,distanceKm:(this.runStats.distance/100).toFixed(1),seed:this.seed,goals:this.goals.filter((g)=>g.complete).length,riderChoices:this.runStats.riderChoices,review:this.dispatchReview()};}
});
