import { Game } from './game-core.js';

export const RIDER_SYSTEM={
  setCourierPath(c,path,targetNodeId){c.path=path;c.pathIndex=path.length>1?1:path.length;c.targetNodeId=targetNodeId;if(path.length<=1)this.arrive(c);},
  remainingPathDistance(c){if(!c?.path?.length||c.pathIndex>=c.path.length)return 0;const target=this.nodeById(c.path[c.pathIndex]);let remaining=target?Math.hypot(target.x-c.x,target.y-c.y):0;for(let i=c.pathIndex+1;i<c.path.length;i++)remaining+=this.edgeByIds(c.path[i-1],c.path[i])?.distance??0;return remaining;},
  courierTaskProgress(c){if(!c?.deliveryId)return 0;const d=this.deliveryById(c.deliveryId);if(!d)return 0;const remaining=this.remainingPathDistance(c);if(c.phase==='pickup'){const total=Math.max(1,d.pickupLegDistance??remaining);return Math.max(0,Math.min(.35,.35*(1-remaining/total)));}if(c.phase==='dropoff'){const total=Math.max(1,d.plannedDistance??remaining);return Math.max(.35,Math.min(1,.35+.65*(1-remaining/total)));}return 0;},
  courierETA(c){if(!c||!(c.phase==='pickup'||c.phase==='dropoff'))return null;const velocity=Math.max(1,c.baseSpeed*c.experience.speed*this.modifiers.speed);return this.remainingPathDistance(c)/velocity;},
  moveCourier(c,dt){if(c.phase!=='pickup'&&c.phase!=='dropoff')return;const target=this.nodeById(c.path[c.pathIndex]);if(!target)return;const dx=target.x-c.x,dy=target.y-c.y,remaining=Math.hypot(dx,dy),from=c.path[Math.max(0,c.pathIndex-1)],edge=this.edgeByIds(from,target.id);if(remaining<.001){this.finishEdge(c,target,edge);return;}c.heading=Math.atan2(dy,dx)+Math.PI/2;const velocity=c.baseSpeed*c.experience.speed*this.modifiers.speed*(edge?.speed??1)*(edge?.eventMultiplier??1),step=Math.min(remaining,velocity*dt);c.x+=dx/remaining*step;c.y+=dy/remaining*step;c.fatigue=Math.min(1,c.fatigue+dt*.00315*c.experience.fatigue*this.modifiers.fatigue);this.runStats.distance+=step;if((edge?.eventMultiplier??1)<.99)this.runStats.eventExposure+=step;if(step>=remaining-.001)this.finishEdge(c,target,edge);},
  finishEdge(c,target,edge){c.x=target.x;c.y=target.y;c.nodeId=target.id;c.pathIndex+=1;const d=this.deliveryById(c.deliveryId);if(d?.pickedUp&&edge)d.edgesTraversed.push(edge.id);if(c.pathIndex>=c.path.length){this.arrive(c);return;}if(this.currentEvent?.state==='active')this.rerouteCourier(c);},
  rerouteCourier(c){if(!c.targetNodeId||c.nodeId===c.targetNodeId)return;const route=this.routeBetween(c.nodeId,c.targetNodeId);if(route.length){c.path=route;c.pathIndex=route.length>1?1:route.length;}},
  arrive(c){const d=this.deliveryById(c.deliveryId);if(!d){this.releaseCourier(c);return;}if(c.phase==='pickup'){d.pickedUp=true;c.phase='dropoff';c.lastMilestone='pickup';c.lastMilestoneAt=this.elapsed;d.edgesTraversed=[];this.setCourierPath(c,this.routeBetween(c.nodeId,d.dropoffId),d.dropoffId);this.logDispatch('pickup',d,{rider:c.name});return;}if(c.phase==='dropoff')this.completeDelivery(c,d);},
  completeDelivery(c,d){d.status='completed';d.completedAt=this.elapsed;this.completed+=1;c.completed+=1;c.lastMilestone='dropoff';c.lastMilestoneAt=this.elapsed;const early=Math.max(0,d.deadlineAt-this.elapsed),quality=Math.max(0,Math.min(1,early/Math.max(1,d.deadlineAt-d.createdAt)));this.cash+=d.reward;this.score+=d.reward*10+Math.round(quality*180);this.reputation=Math.min(100,this.reputation+1.1);c.fatigue=Math.min(1,c.fatigue+.025);this.updateGoals(d);this.logDispatch('complete',d,{rider:c.name,quality});const makeReturn=d.specialId==='return';this.releaseCourier(c,true);if(makeReturn)this.spawnReturnLeg(d);this.recoverFocus();this.maybeAdvanceCity();this.flash(`${c.name} delivered ${d.id.toUpperCase()} · +€${d.reward}`,4);if(this.completed>=this.nextUpgradeAt)this.upgradePending=true;},
  startBreak(c,duration=null){if(!c||c.phase!=='idle')return false;c.radioOn=false;c.phase='break';c.deliberation=null;const fatigueExtra=Math.max(0,c.fatigue-.72)*18;c.breakUntil=this.elapsed+(duration??this.rng.float(13,20)+fatigueExtra);c.breaks+=1;this.runStats.breaks+=1;c.lastDecision='BREAK · RADIO OFF';this.logDispatch('break',null,{rider:c.name});return true;},
  endBreak(c){if(!c||c.phase!=='break')return false;c.radioOn=true;c.phase='idle';c.breakUntil=null;c.fatigue=Math.max(.06,c.fatigue*.3);c.decisionAt=this.elapsed+.24;c.lastDecision='Back on radio';this.logDispatch('radio-on',null,{rider:c.name});return true;},
  shouldTakeBreak(c){if(c.fatigue<.72)return false;const others=this.couriers.filter(r=>r.id!==c.id&&r.radioOn&&r.phase!=='break').length;if(c.fatigue>=.95)return true;if(others<1)return false;return this.rng.chance(.16+(c.fatigue-.72)*1.65);},
  releaseCourier(c,allowBreak=false){c.deliveryId=null;c.phase='idle';c.path=[];c.pathIndex=0;c.targetNodeId=null;c.deliberation=null;if(allowBreak&&this.shouldTakeBreak(c)){this.startBreak(c);return;}c.radioOn=true;c.decisionAt=this.elapsed+this.decisionDelay(c);},
  decisionDelay(c){return Math.max(.26,c.experience.think/this.modifiers.teamSkill*this.rng.float(.7,1.2));},
  breakRemaining(c){return c.phase==='break'?Math.max(0,c.breakUntil-this.elapsed):0;},
  failDelivery(d){if(d.status!=='waiting'&&d.status!=='claimed')return;const c=d.courierId?this.courierById(d.courierId):null,failureKind=d.claimedAt!=null?'claimed-late':d.firstCalledAt==null?'never-called':'called-unclaimed';d.status='failed';d.called=false;d.channel=null;d.failureKind=failureKind;this.failed+=1;const critical=d.type==='medical'||d.type==='coldchain',penalty=critical?15:9;this.reputation=Math.max(0,this.reputation-penalty);this.score=Math.max(0,this.score-penalty*10);this.invalidateDeliberations(d.id);if(c)this.releaseCourier(c,false);this.logDispatch('fail',d,{kind:failureKind,penalty});this.flash(`${d.id.toUpperCase()} missed · -${penalty} REP`,4);if(this.reputation<=0){this.gameOver=true;this.paused=true;this.logDispatch('collapse',d,{});}},
  update(dt){if(this.paused||this.gameOver||this.upgradePending)return;const scaled=dt*this.speed;this.elapsed+=scaled;this.wave=this.cityLevel+Math.floor(this.elapsed/82);this.spawnAccumulator+=scaled;this.updateRoadEvent();const baseInterval=Math.max(3.8,11.8-this.wave*.42),interval=baseInterval/this.modifiers.spawnRate;while(this.spawnAccumulator>=interval){this.spawnAccumulator-=interval;this.spawnDelivery();if(this.wave>=6&&this.rng.chance(Math.min(.22,.02+this.wave*.014)))this.spawnDelivery();}for(const d of [...this.activeDeliveries()])if(this.elapsed>=d.deadlineAt)this.failDelivery(d);for(const c of this.couriers){if(c.phase==='break'){c.fatigue=Math.max(0,c.fatigue-scaled*.04);if(this.elapsed>=c.breakUntil)this.endBreak(c);continue;}if(c.phase==='idle'){c.fatigue=Math.max(0,c.fatigue-scaled*.0011);if(!c.radioOn)continue;if(c.deliberation){const target=this.deliveryById(c.deliberation.deliveryId);if(!target||target.status!=='waiting'||!target.called){c.deliberation=null;c.decisionAt=this.elapsed+.1;}else if(this.elapsed>=c.deliberation.readyAt)this.resolveDeliberation(c);}else if(this.elapsed>=c.decisionAt)this.beginDeliberation(c);}else this.moveCourier(c,scaled);}}
};
Object.assign(Game.prototype,RIDER_SYSTEM);
