import { shortestPath } from './graph.js';
import { Game } from './game-core.js';
Object.assign(Game.prototype,{
  setCourierPath(c,path,targetNodeId){c.path=path;c.pathIndex=path.length>1?1:path.length;c.targetNodeId=targetNodeId;if(path.length<=1)this.arrive(c);},
  moveCourier(c,dt){if(c.phase!=='pickup'&&c.phase!=='dropoff')return;const target=this.nodeById(c.path[c.pathIndex]);if(!target)return;const dx=target.x-c.x,dy=target.y-c.y,remaining=Math.hypot(dx,dy),from=c.path[Math.max(0,c.pathIndex-1)],edge=this.edgeByIds(from,target.id);if(remaining<.001){this.finishEdge(c,target,edge);return;}const velocity=c.baseSpeed*c.experience.speed*this.modifiers.speed*(edge?.speed??1)*(edge?.eventMultiplier??1),step=Math.min(remaining,velocity*dt);c.x+=dx/remaining*step;c.y+=dy/remaining*step;c.fatigue=Math.min(1,c.fatigue+dt*.0038);this.runStats.distance+=step;if((edge?.eventMultiplier??1)<.99)this.runStats.eventExposure+=step;if(step>=remaining-.001)this.finishEdge(c,target,edge);},
  finishEdge(c,target,edge){c.x=target.x;c.y=target.y;c.nodeId=target.id;c.pathIndex+=1;const d=this.deliveryById(c.deliveryId);if(d?.pickedUp&&edge)d.edgesTraversed.push(edge.id);if(c.pathIndex>=c.path.length){this.arrive(c);return;}if(this.currentEvent?.state==='active')this.rerouteCourier(c);},
  rerouteCourier(c){if(!c.targetNodeId||c.nodeId===c.targetNodeId)return;const route=shortestPath(this.nodes,this.edges,c.nodeId,c.targetNodeId,this.edgeCost.bind(this));if(route.length){c.path=route;c.pathIndex=route.length>1?1:route.length;}},
  arrive(c){const d=this.deliveryById(c.deliveryId);if(!d){this.releaseCourier(c);return;}if(c.phase==='pickup'){d.pickedUp=true;c.phase='dropoff';d.edgesTraversed=[];this.setCourierPath(c,shortestPath(this.nodes,this.edges,c.nodeId,d.dropoffId,this.edgeCost.bind(this)),d.dropoffId);return;}if(c.phase==='dropoff')this.completeDelivery(c,d);},
  completeDelivery(c,d){d.status='completed';d.completedAt=this.elapsed;this.completed+=1;c.completed+=1;const early=Math.max(0,d.deadlineAt-this.elapsed);this.cash+=d.reward;this.score+=d.reward*10+Math.round(early*3);this.reputation=Math.min(100,this.reputation+1.35);this.updateGoals(d);this.logDispatch('complete',d,{rider:c.name});this.releaseCourier(c,true);this.flash(`${c.name} delivered ${d.id.toUpperCase()} · +€${d.reward}`);if(this.completed>=this.nextUpgradeAt)this.upgradePending=true;},
  startBreak(c,duration=null){if(!c||c.phase!=='idle')return false;c.radioOn=false;c.phase='break';c.deliberation=null;c.breakUntil=this.elapsed+(duration??this.rng.float(14,24));c.breaks+=1;this.runStats.breaks+=1;c.lastDecision='Break · radio off';this.logDispatch('break',null,{rider:c.name});return true;},
  endBreak(c){if(!c||c.phase!=='break')return false;c.radioOn=true;c.phase='idle';c.breakUntil=null;c.fatigue=Math.max(.08,c.fatigue*.35);c.decisionAt=this.elapsed+.25;c.lastDecision='Back on radio.';this.logDispatch('radio-on',null,{rider:c.name});return true;},
  releaseCourier(c,allowBreak=false){c.deliveryId=null;c.phase='idle';c.path=[];c.pathIndex=0;c.targetNodeId=null;c.deliberation=null;const shouldBreak=allowBreak&&(c.fatigue>=.9||(c.fatigue>=.72&&this.rng.chance(.34+c.fatigue*.22)));if(shouldBreak){this.startBreak(c);return;}c.radioOn=true;c.decisionAt=this.elapsed+this.decisionDelay(c);},
  decisionDelay(c){return Math.max(.28,c.experience.think/this.modifiers.teamSkill*this.rng.float(.72,1.28));},
  breakRemaining(c){return c.phase==='break'?Math.max(0,c.breakUntil-this.elapsed):0;},
  failDelivery(d){if(d.status!=='waiting'&&d.status!=='claimed')return;const c=d.courierId?this.courierById(d.courierId):null,failureKind=d.claimedAt!=null?'claimed-late':d.firstCalledAt==null?'never-called':'called-unclaimed';d.status='failed';d.called=false;d.channel=null;d.failureKind=failureKind;this.failed+=1;const penalty=d.type==='medical'?18:11;this.reputation=Math.max(0,this.reputation-penalty);this.score=Math.max(0,this.score-penalty*12);this.invalidateDeliberations(d.id);if(c)this.releaseCourier(c,false);this.logDispatch('fail',d,{kind:failureKind,penalty});this.flash(`${d.id.toUpperCase()} missed · -${penalty}% reputation`);if(this.reputation<=0){this.gameOver=true;this.paused=true;}},
  update(dt){if(this.paused||this.gameOver||this.upgradePending)return;const scaled=dt*this.speed;this.elapsed+=scaled;this.wave=1+Math.floor(this.elapsed/62);this.spawnAccumulator+=scaled;this.updateRoadEvent();const interval=Math.max(3.2,10-this.wave*.48);while(this.spawnAccumulator>=interval){this.spawnAccumulator-=interval;this.spawnDelivery();if(this.wave>=4&&this.rng.chance(Math.min(.3,.05+this.wave*.02)))this.spawnDelivery();}for(const d of [...this.activeDeliveries()])if(this.elapsed>=d.deadlineAt)this.failDelivery(d);for(const c of this.couriers){if(c.phase==='break'){c.fatigue=Math.max(0,c.fatigue-scaled*.035);if(this.elapsed>=c.breakUntil)this.endBreak(c);continue;}if(c.phase==='idle'){c.fatigue=Math.max(0,c.fatigue-scaled*.0008);if(!c.radioOn)continue;if(c.deliberation){const target=this.deliveryById(c.deliberation.deliveryId);if(!target||target.status!=='waiting'||!target.called){c.deliberation=null;c.decisionAt=this.elapsed+.12;}else if(this.elapsed>=c.deliberation.readyAt)this.resolveDeliberation(c);}else if(this.elapsed>=c.decisionAt)this.beginDeliberation(c);}else this.moveCourier(c,scaled);}}
});
