import { distance, shortestPath } from './graph.js';
import { Game } from './game-core.js';
import { RADIO_CHANNELS } from './game-data.js';
Object.assign(Game.prototype,{
  setChannel(deliveryId,channelId){const d=this.deliveryById(deliveryId);if(!d||d.status!=='waiting')return false;if(channelId===null||channelId==='off'){if(!d.called)return true;const previous=d.channel;d.called=false;d.channel=null;d.callHistory.push({at:this.elapsed,channel:null});this.invalidateDeliberations(d.id);this.logDispatch('uncall',d,{channel:previous});this.flash(`Radio withdrawn · ${this.deliveryLabel(d)}`);return true;}const channel=RADIO_CHANNELS[channelId];if(!channel)return false;const nextUsed=this.radioUsed()-this.radioCost(d)+channel.cost;if(nextUsed>this.radioSlots){this.runStats.radioDenied+=1;this.logDispatch('radio-denied',d,{channel:channelId});this.flash(`Radio full · ${channel.short} needs ${channel.cost}`);return false;}const wasCalled=d.called,previous=d.channel;d.called=true;d.channel=channelId;d.firstCalledAt??=this.elapsed;d.callHistory.push({at:this.elapsed,channel:channelId});this.selectedDeliveryId=d.id;this.runStats.peakRadio=Math.max(this.runStats.peakRadio,this.radioUsed());this.logDispatch(wasCalled?'channel':'call',d,{channel:channelId,previous});if(previous&&previous!==channelId)this.invalidateDeliberations(d.id);for(const c of this.availableRiders())c.decisionAt=Math.min(c.decisionAt,this.elapsed+.2);this.flash(`${channel.short} · ${this.deliveryLabel(d)}`);return true;},
  toggleCall(id){const d=this.deliveryById(id);return d?.called?this.setChannel(id,'off'):this.setChannel(id,'open');},
  invalidateDeliberations(id){for(const c of this.couriers)if(c.deliberation?.deliveryId===id){c.deliberation=null;c.decisionAt=this.elapsed+.12;}},
  selectDelivery(id){this.selectedDeliveryId=this.selectedDeliveryId===id?null:id;},
  selectCourier(id){this.selectedCourierId=this.selectedCourierId===id?null:id;},
  routeTravelCost(startId,goalId){const route=shortestPath(this.nodes,this.edges,startId,goalId,this.edgeCost.bind(this));if(!route.length)return Infinity;let total=0;for(let i=1;i<route.length;i+=1){const e=this.edgeByIds(route[i-1],route[i]);total+=e?this.edgeCost(e):0;}return total;},
  courierChoiceScore(c,d,withNoise=true){if(!c.radioOn||c.phase!=='idle')return-Infinity;const pickup=this.nodeById(d.pickupId),current=this.nodeById(c.nodeId),travel=Math.max(1,this.routeTravelCost(c.nodeId,pickup.id)),closeness=1/(1+travel/180),urgency=1-this.urgency(d),reward=Math.min(1.7,d.reward/26),medical=d.type==='medical'?1:0,landmark=pickup.kind==='landmark'||this.nodeById(d.dropoffId).kind==='landmark'?1:0,same=current.districtId&&current.districtId===pickup.districtId?1:0,longRide=Math.min(1,travel/560),w=c.personality.weights;let score=closeness*(w.distance??0)+urgency*(w.urgency??0)+reward*(w.reward??0)+medical*(w.medical??0)+landmark*(w.landmark??0)+same*(w.sameDistrict??0)+longRide*(w.longRide??0);if(d.channel==='priority')score+=.56;if(d.channel==='local')score+=same?.72:closeness>.58?.26:-.22;score-=c.fatigue*.24;if(withNoise)score+=this.rng.float(-c.experience.noise/this.modifiers.teamSkill,c.experience.noise/this.modifiers.teamSkill);return score;},
  predictCall(c){if(!c||c.phase!=='idle'||!c.radioOn)return null;if(c.deliberation){const d=this.deliveryById(c.deliberation.deliveryId);if(d?.called&&d.status==='waiting')return{delivery:d,score:c.deliberation.score,deliberating:true};}const calls=this.calledDeliveries();if(!calls.length)return null;return calls.map((d)=>({delivery:d,score:this.courierChoiceScore(c,d,false)})).sort((a,b)=>b.score-a.score)[0]??null;},
  beginDeliberation(c){if(!c.radioOn||c.phase!=='idle')return false;const calls=this.calledDeliveries();if(!calls.length){c.lastDecision='Radio on · no live calls.';c.decisionAt=this.elapsed+this.decisionDelay(c);return false;}const ranked=calls.map((d)=>({delivery:d,score:this.courierChoiceScore(c,d,true)})).sort((a,b)=>b.score-a.score),best=ranked[0];if(!best||best.score<.28){c.lastDecision='Holding for a better call.';c.decisionAt=this.elapsed+this.decisionDelay(c);return false;}const duration=Math.max(.34,c.experience.think/this.modifiers.teamSkill*this.rng.float(.52,.88));c.deliberation={deliveryId:best.delivery.id,startedAt:this.elapsed,readyAt:this.elapsed+duration,score:best.score,reason:this.choiceReason(c,best.delivery)};c.lastDecision=`Considering ${best.delivery.id.toUpperCase()} · ${c.deliberation.reason}`;return true;},
  deliberationProgress(c){if(!c?.deliberation)return 0;const total=Math.max(.001,c.deliberation.readyAt-c.deliberation.startedAt);return Math.max(0,Math.min(1,(this.elapsed-c.deliberation.startedAt)/total));},
  resolveDeliberation(c){const thought=c.deliberation;if(!thought)return false;const d=this.deliveryById(thought.deliveryId);c.deliberation=null;if(!d||d.status!=='waiting'||!d.called||!c.radioOn){c.decisionAt=this.elapsed+.16;return false;}return this.claim(c,d,thought.score);},
  claim(c,d,score=0){if(!c?.radioOn||c.phase!=='idle'||!d?.called||d.status!=='waiting')return false;const path=shortestPath(this.nodes,this.edges,c.nodeId,d.pickupId,this.edgeCost.bind(this));if(!path.length)return false;d.status='claimed';d.called=false;d.claimedAt=this.elapsed;d.courierId=c.id;c.deliveryId=d.id;c.phase='pickup';c.deliberation=null;this.setCourierPath(c,path,d.pickupId);c.lastDecision=`Took ${d.id.toUpperCase()} · ${this.choiceReason(c,d)}`;this.runStats.riderChoices+=1;this.logDispatch('claim',d,{rider:c.name,score});this.invalidateDeliberations(d.id);this.flash(`${c.name} chose ${this.deliveryLabel(d)}`);return true;},
  choiceReason(c,d){const pickup=this.nodeById(d.pickupId),current=this.nodeById(c.nodeId);if(d.channel==='priority')return'priority signal';if(d.channel==='local'&&current.districtId===pickup.districtId)return'local call';if(d.type==='medical'&&c.personality.id==='guardian')return'medical priority';if(this.urgency(d)<.34)return'deadline pressure';if(c.personality.id==='earner')return`€${d.reward} payout`;if(distance(current,pickup)<160)return'close pickup';return c.personality.title.toLowerCase();}
});
