import { BERLIN } from './berlin.js';
import { Game } from './game-core.js';
import { COURIER_NAMES,ROAD_EVENT_TYPES,UPGRADES } from './game-data.js';
import { allCityEventTypes } from './event-data.js';

Object.assign(Game.prototype,{
  scheduleRoadEvent(forceId=null){
    const templates=allCityEventTypes(ROAD_EVENT_TYPES),template=forceId?templates.find(item=>item.id===forceId):this.rng.pick(templates);if(!template)return false;
    let graphEdges=[],visualIds=[],place='Berlin',districtId=null;
    if(template.kind==='demand'){
      const districts=this.districts.filter(d=>(d.unlockLevel??1)<=this.cityLevel),district=this.rng.pick(districts);if(!district)return false;districtId=district.id;place=district.name;
    }else if(template.bridgeOnly){
      const bridges=BERLIN.bridges.filter(bridge=>this.visualEdges.some(v=>v.bridgeId===bridge.id&&this.visualEdgePlayable(v.id))),bridge=this.rng.pick(bridges);if(bridge){visualIds=this.visualEdges.filter(v=>v.bridgeId===bridge.id&&this.visualEdgePlayable(v.id)).map(v=>v.id);graphEdges=this.edges.filter(e=>visualIds.includes(e.visualId)&&this.edgePlayable(e));place=bridge.short;}
    }else if(template.weatherCell){
      const districts=this.districts.filter(d=>(d.unlockLevel??1)<=this.cityLevel),district=this.rng.pick(districts);if(district){districtId=district.id;const candidates=this.visualEdges.filter(e=>{if(e.roadClass==='connector'||!this.visualEdgePlayable(e.id))return false;const a=this.nodeById(e.a),b=this.nodeById(e.b);return a?.districtId===district.id||b?.districtId===district.id;}),count=Math.max(3,Math.round(this.rng.float(template.edgeCount?.[0]??5,(template.edgeCount?.[1]??8)+.49))),selected=this.rng.shuffle(candidates).slice(0,count);visualIds=selected.map(e=>e.id);graphEdges=this.edges.filter(e=>visualIds.includes(e.visualId)&&this.edgePlayable(e));place=district.name;}
    }else{
      const candidates=this.visualEdges.filter(e=>e.roadClass!=='connector'&&!e.bikeLane&&this.visualEdgePlayable(e.id)),selected=this.rng.shuffle(candidates).slice(0,this.rng.chance(.3)?2:1);visualIds=selected.map(e=>e.id);graphEdges=this.edges.filter(e=>visualIds.includes(e.visualId)&&this.edgePlayable(e));place=selected[0]?.streetName??'Berlin';
    }
    if(template.kind==='route'&&!graphEdges.length){this.nextEventAt=this.elapsed+35;return false;}
    const startsAt=this.nextEventAt,duration=this.rng.float(...template.duration);this.currentEvent={id:`event-${Math.round(startsAt)}-${template.id}`,type:template.id,kind:template.kind,title:template.title,detail:template.forecast,place,districtId,state:'forecast',startsAt,endsAt:startsAt+duration,factor:template.factor??1,edgeIds:graphEdges.map(e=>e.id),visualIds,advisory:false,prepared:false,burst:template.burst??0,label:template.label??null,glyph:template.glyph??null,generatedJobs:0};this.logDispatch('event-forecast',null,{title:template.title,place,kind:template.kind});this.flash(`${template.title} forecast · ${place}`,5);return true;
  },
  spawnEventDemand(ev){
    if(!ev||ev.kind!=='demand')return 0;const pickups=this.playableAddressNodes().filter(n=>n.districtId===ev.districtId);if(!pickups.length)return 0;const target=Math.max(1,(ev.burst??3)-(ev.prepared?1:0));let spawned=0;
    for(let i=0;i<target;i++){const pickup=this.rng.pick(pickups),dropoff=this.randomAddress(pickup?.id);if(!pickup||!dropoff)continue;const typeKey=this.weightedDeliveryType(),ok=this.spawnDelivery({pickupId:pickup.id,dropoffId:dropoff.id,typeKey,special:false,specialId:`event-${ev.type}`,specialLabel:ev.label??'SURGE',specialGlyph:ev.glyph??'+',specialDesc:ev.detail});if(!ok)continue;const d=this.deliveries.at(-1);d.eventId=ev.id;d.eventPrepared=Boolean(ev.prepared);d.reward+=ev.type==='transit-outage'?4:2;if(ev.prepared)d.deadlineAt+=14;spawned++;}
    ev.generatedJobs=spawned;this.logDispatch('event-demand',null,{title:ev.title,place:ev.place,jobs:spawned,prepared:ev.prepared});return spawned;
  },
  updateRoadEvent(){
    if(!this.currentEvent&&this.elapsed>=this.nextEventAt-10)this.scheduleRoadEvent();const ev=this.currentEvent;if(!ev)return;
    if(ev.state==='forecast'&&this.elapsed>=ev.startsAt){ev.state='active';if(ev.kind==='route'){const factor=ev.prepared?ev.factor+(1-ev.factor)*.35:ev.factor;ev.appliedFactor=factor;for(const e of this.edges)if(ev.edgeIds.includes(e.id))e.eventMultiplier=factor;for(const c of this.couriers)if(c.phase==='pickup'||c.phase==='dropoff')this.rerouteCourier(c);}else this.spawnEventDemand(ev);this.logDispatch('event-start',null,{title:ev.title,place:ev.place,kind:ev.kind,prepared:ev.prepared});this.flash(`${ev.title} ACTIVE · ${ev.place}`,5);}
    if(ev.state==='active'&&this.elapsed>=ev.endsAt){if(ev.kind==='route')for(const e of this.edges)if(ev.edgeIds.includes(e.id))e.eventMultiplier=1;this.logDispatch('event-end',null,{title:ev.title,place:ev.place,kind:ev.kind});this.currentEvent=null;this.nextEventAt=this.elapsed+46+this.rng.float(0,32);}
  },
  generateGoals(){const unlockedVisual=this.visualEdges.filter(e=>e.roadClass!=='connector'&&this.visualEdgePlayable(e.id)),street=this.rng.pick([...new Set(unlockedVisual.map(e=>e.streetName))]),district=this.rng.pick(this.districts.filter(d=>(d.unlockLevel??1)<=this.cityLevel));return[
    {id:'street',type:'street',targetId:street,label:`Work ${street}`,detail:`4 jobs touch ${street}.`,progress:0,target:4,reward:18,complete:false},
    {id:'district',type:'district',targetId:district.id,label:`Cover ${district.name}`,detail:`6 jobs touch this area.`,progress:0,target:6,reward:20,complete:false},
    {id:'reliability',type:'reliability',label:'Reliable radio',detail:'Complete 12 deliveries.',progress:0,target:12,reward:24,complete:false}
  ];},
  addExpansionGoals(){if(this.cityLevel>=2&&!this.goals.some(g=>g.type==='bridge')){const bridges=BERLIN.bridges.filter(bridge=>this.visualEdges.some(v=>v.bridgeId===bridge.id&&this.visualEdgePlayable(v.id))),bridge=this.rng.pick(bridges);if(bridge)this.goals.push({id:'bridge',type:'bridge',targetId:bridge.id,label:`Cross ${bridge.short}`,detail:'3 completed routes use this bridge.',progress:0,target:3,reward:24,complete:false});}if(this.cityLevel>=3&&!this.goals.some(g=>g.type==='cross'))this.goals.push({id:'cross',type:'cross',label:'Cross the Ring desk',detail:'Complete 8 cross-area deliveries.',progress:0,target:8,reward:30,complete:false});},
  updateGoals(d){for(const g of this.goals){if(g.complete)continue;const p=this.nodeById(d.pickupId),q=this.nodeById(d.dropoffId),bridges=new Set(d.edgesTraversed.map(id=>this.edges.find(e=>e.id===id)?.bridgeId).filter(Boolean));let hit=false;if(g.type==='street')hit=p?.streetName===g.targetId||q?.streetName===g.targetId;if(g.type==='district')hit=p?.districtId===g.targetId||q?.districtId===g.targetId;if(g.type==='bridge')hit=bridges.has(g.targetId);if(g.type==='reliability')hit=true;if(g.type==='cross')hit=p?.districtId&&q?.districtId&&p.districtId!==q.districtId;if(!hit)continue;g.progress+=1;if(g.progress>=g.target){g.complete=true;this.cash+=g.reward;this.score+=g.reward*20;this.reputation=Math.min(100,this.reputation+7);this.logDispatch('goal',d,{goal:g.label});this.flash(`GOAL · ${g.label} · +€${g.reward}`,5);}}},
  getUpgradeChoices(){return this.rng.shuffle(UPGRADES.filter(u=>u.id!=='rider'||this.courierSerial<COURIER_NAMES.length)).slice(0,3);},
  applyUpgrade(id){const u=UPGRADES.find(x=>x.id===id);if(!u||!this.upgradePending)return false;u.apply(this);this.upgradePending=false;this.nextUpgradeAt+=8+Math.floor(this.nextUpgradeAt/16);this.logDispatch('upgrade',null,{upgrade:u.title});this.flash(`${u.title} added`,4);return true;},
  deliveryLabel(d){return `${d.pickupAddress} → ${d.dropoffAddress}`;},
  nearestIdleDistance(d){const riders=this.availableRiders();if(!riders.length)return null;return Math.min(...riders.map(c=>this.routeTravelCost(c.nodeId,d.pickupId)));},
  flash(message,duration=4){this.notice=message;this.noticeUntil=this.elapsed+duration;},
  logDispatch(action,delivery=null,extra={}){this.dispatchLog.push({at:this.elapsed,action,deliveryId:delivery?.id??null,pickup:delivery?.pickupAddress??null,dropoff:delivery?.dropoffAddress??null,radioUsed:this.radioUsed(),cityLevel:this.cityLevel,...extra});if(this.dispatchLog.length>300)this.dispatchLog.splice(0,this.dispatchLog.length-300);},
  nearestEntity(x,y,maxDistance=28){let best=null;for(const d of this.activeDeliveries()){const n=this.nodeById(d.pickedUp?d.dropoffId:d.pickupId),dd=Math.hypot(n.x-x,n.y-y);if(dd<=maxDistance&&(!best||dd<best.distance))best={type:'delivery',id:d.id,distance:dd};}for(const c of this.couriers){const dd=Math.hypot(c.x-x,c.y-y);if(dd<=maxDistance&&(!best||dd<best.distance))best={type:'courier',id:c.id,distance:dd};}return best;},
  dispatchReview(){const done=this.deliveries.filter(d=>['completed','failed'].includes(d.status)),fail=done.filter(d=>d.status==='failed'),never=fail.filter(d=>d.failureKind==='never-called').length,unclaimed=fail.filter(d=>d.failureKind==='called-unclaimed').length,late=fail.filter(d=>d.failureKind==='claimed-late').length,top=[...this.couriers].sort((a,b)=>b.completed-a.completed)[0],advice=[];if(never>=2)advice.push(`${never} jobs expired before broadcast. Hold less low-risk work.`);if(unclaimed>=2)advice.push(`${unclaimed} broadcasts had no taker. Match channel, payout and rider position.`);if(late>=2)advice.push(`${late} accepted jobs still arrived late. Client calls or bonuses may have been cheaper.`);if(this.runStats.radioDenied>=2)advice.push(`Bandwidth blocked ${this.runStats.radioDenied} radio changes. Keep one slot flexible.`);if(this.runStats.breaks>=2)advice.push(`${this.runStats.breaks} breaks reduced coverage. Read energy before opening distant calls.`);if(this.runStats.toolsUsed===0&&this.completed>=8)advice.push('You never used dispatch tools. Bonuses, client calls and event responses can reshape a bad desk.');if(!advice.length)advice.push('The desk stayed disciplined. Improve timing around events and rider energy.');return{neverCalled:never,calledUnclaimed:unclaimed,claimedLate:late,radioDenied:this.runStats.radioDenied,breaks:this.runStats.breaks,toolsUsed:this.runStats.toolsUsed,eventsPrepared:this.runStats.eventsPrepared??0,stage:this.currentStage().name,topRider:top?`${top.name} · ${top.completed} deliveries`:'—',advice};},
  summary(){return{score:Math.round(this.score),completed:this.completed,failed:this.failed,wave:this.wave,distanceKm:(this.runStats.distance/100).toFixed(1),seed:this.seed,goals:this.goals.filter(g=>g.complete).length,riderChoices:this.runStats.riderChoices,cityLevel:this.cityLevel,review:this.dispatchReview()};}
});
