import { RNG, createSeed } from './rng.js';
import { buildAdjacency, distance, shortestPath } from './graph.js';
import { BERLIN } from './berlin.js';
import { COURIER_COLORS,COURIER_NAMES,DELIVERY_TYPES,EXPERIENCE,PERSONALITIES,RADIO_CHANNELS,RUN_TRAITS,edgeKey,weightedPick } from './game-data.js';
export class Game{
constructor({seed=createSeed(),width=BERLIN.width,height=BERLIN.height}={}){this.seed=seed;this.rng=new RNG(seed);this.width=width;this.height=height;this.elapsed=0;this.score=0;this.cash=0;this.reputation=100;this.completed=0;this.failed=0;this.wave=1;this.speed=1;this.paused=false;this.gameOver=false;this.upgradePending=false;this.nextUpgradeAt=8;this.deliverySerial=0;this.courierSerial=0;this.spawnAccumulator=0;this.selectedDeliveryId=null;this.selectedCourierId=null;this.radioSlots=4;this.notice='Broadcast jobs. Riders choose for themselves.';this.noticeUntil=9;this.modifiers={speed:1,deadline:1,reward:1,teamSkill:1,landmarkBias:.27};this.runStats={peakActive:0,peakRadio:0,distance:0,riderChoices:0,radioDenied:0,eventExposure:0,breaks:0};this.dispatchLog=[];this.generateBerlin();this.deliveries=[];this.couriers=[];this.runTrait=this.rng.pick(RUN_TRAITS);this.runTrait.apply(this);for(let i=0;i<3;i+=1)this.addCourier();this.goals=this.generateGoals();this.currentEvent=null;this.nextEventAt=52+this.rng.float(0,20);for(let i=0;i<4;i+=1)this.spawnDelivery();}
generateBerlin(){this.districts=BERLIN.districts.map((d)=>({...d,polygon:d.polygon.map((p)=>[...p])}));this.parks=BERLIN.parks.map((p)=>({...p,polygon:p.polygon.map((q)=>[...q])}));this.river=BERLIN.river.map((p)=>[...p]);this.canal=BERLIN.canal.map((p)=>[...p]);this.landmarks=BERLIN.landmarks.map((l)=>({...l}));this.nodes=BERLIN.nodes.map((n)=>({...n}));this.edges=[];const byId=new Map(this.nodes.map((n)=>[n.id,n])),seen=new Map(),bridgeMap=new Map(BERLIN.bridges.map((b)=>[edgeKey(...b.edge),b.id])),classSpeed={arterial:1.02,primary:1,secondary:.97,bridge:.98};for(const street of BERLIN.streets)for(let i=1;i<street.nodes.length;i+=1){const aId=street.nodes[i-1],bId=street.nodes[i],a=byId.get(aId),b=byId.get(bId);if(!a||!b)continue;const key=edgeKey(aId,bId);if(seen.has(key)){const e=seen.get(key);e.streetNames.push(street.name);if(street.class==='arterial')e.roadClass='arterial';continue;}const e={id:`e${this.edges.length}`,a:aId,b:bId,distance:distance(a,b),speed:classSpeed[street.class]??1,bikeLane:false,eventMultiplier:1,roadClass:street.class,streetName:street.name,streetNames:[street.name],bridgeId:bridgeMap.get(key)??null};this.edges.push(e);seen.set(key,e);}this.ensureConnectivity();this.depotNodeId='checkpoint';}
ensureConnectivity(){const components=()=>{const adjacency=buildAdjacency(this.nodes,this.edges),remaining=new Set(this.nodes.map((n)=>n.id)),groups=[];while(remaining.size){const first=remaining.values().next().value,stack=[first],group=[];remaining.delete(first);while(stack.length){const id=stack.pop();group.push(id);for(const{to}of adjacency.get(id)??[])if(remaining.has(to)){remaining.delete(to);stack.push(to);}}groups.push(group);}return groups;};let groups=components();while(groups.length>1){const main=groups[0].map((id)=>this.nodeById(id));let best=null;for(let gi=1;gi<groups.length;gi+=1)for(const a of main)for(const id of groups[gi]){const b=this.nodeById(id),d=distance(a,b);if(!best||d<best.d)best={a,b,d};}this.edges.push({id:`e${this.edges.length}`,a:best.a.id,b:best.b.id,distance:best.d,speed:.92,bikeLane:false,eventMultiplier:1,roadClass:'connector',streetName:'connector',streetNames:['connector'],bridgeId:null});groups=components();}}
promoteBikeLanes(count,speed=1.4){for(const e of this.rng.shuffle(this.edges.filter((x)=>x.roadClass!=='connector')).slice(0,count)){e.speed=Math.max(e.speed,speed);e.bikeLane=true;}}
nodeById(id){return this.nodes.find((n)=>n.id===id);}deliveryById(id){return this.deliveries.find((d)=>d.id===id);}courierById(id){return this.couriers.find((c)=>c.id===id);}edgeByIds(a,b){return this.edges.find((e)=>edgeKey(e.a,e.b)===edgeKey(a,b));}
addCourier(){if(this.courierSerial>=COURIER_NAMES.length)return false;const depot=this.nodeById(this.depotNodeId),index=this.courierSerial++,personality=this.rng.pick(PERSONALITIES),experience=weightedPick(this.rng,EXPERIENCE,(e)=>[0,3.1,4.1,2.8,1.2][e.level]),homeDistrict=this.rng.pick(this.districts).id;this.couriers.push({id:`c${index}`,name:COURIER_NAMES[index],color:COURIER_COLORS[index],personality,experience,homeDistrict,nodeId:depot.id,x:depot.x+(index-1)*9,y:depot.y+(index-1)*7,path:[],pathIndex:0,targetNodeId:null,deliveryId:null,phase:'idle',baseSpeed:62+this.rng.float(-3,5),decisionAt:this.elapsed+this.rng.float(.35,1.2),deliberation:null,lastDecision:'Radio on · listening.',completed:0,radioOn:true,fatigue:this.rng.float(.04,.14),breakUntil:null,breaks:0});return true;}
randomEndpoint(excludeId=null){const candidates=this.nodes.filter((n)=>n.id!==excludeId&&n.id!==this.depotNodeId);const landmarkGoal=this.goals?.find((g)=>g.type==='landmark'&&!g.complete);if(landmarkGoal&&this.rng.chance(.16)){const target=candidates.find((n)=>n.landmarkId===landmarkGoal.targetId);if(target)return target;}const districtGoal=this.goals?.find((g)=>g.type==='district'&&!g.complete);if(districtGoal&&this.rng.chance(.1)){const local=candidates.filter((n)=>n.districtId===districtGoal.targetId);if(local.length)return this.rng.pick(local);}const landmarks=candidates.filter((n)=>n.kind==='landmark');if(landmarks.length&&this.rng.chance(this.modifiers.landmarkBias))return this.rng.pick(landmarks);return this.rng.pick(candidates);}
spawnDelivery(){if(this.activeDeliveries().length>=32)return;const pickup=this.randomEndpoint(),dropoff=this.randomEndpoint(pickup?.id);if(!pickup||!dropoff)return;const typeKey=this.rng.pick(Object.keys(DELIVERY_TYPES)),type=DELIVERY_TYPES[typeKey],route=shortestPath(this.nodes,this.edges,pickup.id,dropoff.id,this.edgeCost.bind(this));if(!route.length)return;const routeDistance=this.pathDistance(route),deadline=type.baseDeadline*this.modifiers.deadline*(.82+routeDistance/820)/(1+(this.wave-1)*.017),id=`d${this.deliverySerial++}`;this.deliveries.push({id,type:typeKey,pickupId:pickup.id,dropoffId:dropoff.id,createdAt:this.elapsed,deadlineAt:this.elapsed+deadline,reward:Math.round((type.reward+routeDistance/95)*this.modifiers.reward),status:'waiting',called:false,channel:null,courierId:null,pickedUp:false,firstCalledAt:null,claimedAt:null,edgesTraversed:[],callHistory:[]});this.runStats.peakActive=Math.max(this.runStats.peakActive,this.activeDeliveries().length);}
activeDeliveries(){return this.deliveries.filter((d)=>d.status==='waiting'||d.status==='claimed');}calledDeliveries(){return this.deliveries.filter((d)=>d.status==='waiting'&&d.called);}calledCount(){return this.calledDeliveries().length;}radioCost(d){return d?.called?(RADIO_CHANNELS[d.channel]?.cost??1):0;}radioUsed(){return this.calledDeliveries().reduce((s,d)=>s+this.radioCost(d),0);}availableRiders(){return this.couriers.filter((c)=>c.phase==='idle'&&c.radioOn);}
edgeCost(e){return e.distance/Math.max(.18,e.speed*(e.eventMultiplier??1));}pathDistance(path){let total=0;for(let i=1;i<(path?.length??0);i+=1)total+=this.edgeByIds(path[i-1],path[i])?.distance??0;return total;}urgency(d){const total=Math.max(1,d.deadlineAt-d.createdAt);return Math.max(0,Math.min(1,(d.deadlineAt-this.elapsed)/total));}
}
