import { RNG,createSeed } from './rng.js';
import { createGraphIndex,shortestPathIndexed } from './graph.js';
import { BERLIN } from './berlin.js';
import { COURIER_COLORS,COURIER_NAMES,DELIVERY_TYPES,EXPERIENCE,PERSONALITIES,RADIO_CHANNELS,RUN_CONTRACTS,RUN_TRAITS,weightedPick } from './game-data.js';
export class Game{
constructor({seed=createSeed(),width=BERLIN.width,height=BERLIN.height}={}){
this.seed=seed;this.rng=new RNG(seed);this.width=width;this.height=height;this.elapsed=0;this.score=0;this.cash=0;this.reputation=100;this.completed=0;this.failed=0;this.wave=1;this.speed=1;this.paused=false;this.gameOver=false;this.upgradePending=false;this.nextUpgradeAt=8;this.deliverySerial=0;this.courierSerial=0;this.spawnAccumulator=0;this.selectedDeliveryId=null;this.selectedCourierId=null;this.radioSlots=4;this.notice='Read the city. Broadcast the right work. Riders decide.';this.noticeUntil=10;
this.modifiers={speed:1,deadline:1,reward:1,teamSkill:1,spawnRate:1,fatigue:1};this.runStats={peakActive:0,peakRadio:0,distance:0,riderChoices:0,radioDenied:0,eventExposure:0,breaks:0};this.dispatchLog=[];
this.generateBerlin();this.deliveries=[];this.couriers=[];this.runTrait=this.rng.pick(RUN_TRAITS);this.runContract=this.rng.pick(RUN_CONTRACTS);this.runTrait.apply(this);this.applyContract(this.runContract);for(let i=0;i<3;i+=1)this.addCourier();this.goals=this.generateGoals();this.currentEvent=null;this.nextEventAt=56+this.rng.float(0,20);for(let i=0;i<5;i+=1)this.spawnDelivery();}
generateBerlin(){this.districts=BERLIN.districts.map((d)=>({...d,polygon:d.polygon.map((p)=>[...p])}));this.parks=BERLIN.parks.map((p)=>({...p,polygon:p.polygon.map((q)=>[...q])}));this.river=BERLIN.river.map((p)=>[...p]);this.canal=BERLIN.canal.map((p)=>[...p]);this.landmarks=BERLIN.landmarks.map((l)=>({...l}));this.nodes=BERLIN.nodes.map((n)=>({...n,address:n.address?{...n.address}:n.address}));this.edges=BERLIN.edges.map((e)=>({...e,streetNames:[...(e.streetNames??[e.streetName])]}));this.visualEdges=BERLIN.visualEdges.map((e)=>({...e,streetNames:[...(e.streetNames??[e.streetName])]}));this.addressNodes=this.nodes.filter((n)=>n.kind==='address');this.streetCatalog=[...BERLIN.streetCatalog];this.nodeMap=new Map(this.nodes.map((n)=>[n.id,n]));this.edgeMap=new Map();for(const e of this.edges)this.edgeMap.set(this.edgeKey(e.a,e.b),e);this.graph=createGraphIndex(this.nodes,this.edges);this.depotNodeId=this.landmarks.find((l)=>l.id==='checkpoint')?.addressNodeId??this.addressNodes[0]?.id;}
applyContract(contract){this.modifiers.reward*=contract.reward??1;this.modifiers.deadline*=contract.deadline??1;this.modifiers.spawnRate*=contract.spawnRate??1;}
edgeKey(a,b){return[a,b].sort().join('|');}
nodeById(id){return this.nodeMap.get(id);}deliveryById(id){return this.deliveries.find((d)=>d.id===id);}courierById(id){return this.couriers.find((c)=>c.id===id);}edgeByIds(a,b){return this.edgeMap.get(this.edgeKey(a,b));}
routeBetween(startId,goalId){return shortestPathIndexed(this.graph,startId,goalId,this.edgeCost.bind(this));}
routeDistance(path){let total=0;for(let i=1;i<(path?.length??0);i++)total+=this.edgeByIds(path[i-1],path[i])?.distance??0;return total;}
routeStreets(path){const result=[];for(let i=1;i<(path?.length??0);i++){const name=this.edgeByIds(path[i-1],path[i])?.streetName;if(name&&result.at(-1)!==name)result.push(name);}return result;}
routeTravelCost(startId,goalId){const path=this.routeBetween(startId,goalId);if(!path.length)return Infinity;let total=0;for(let i=1;i<path.length;i++){const e=this.edgeByIds(path[i-1],path[i]);if(e)total+=this.edgeCost(e);}return total;}
edgeCost(e){return e.distance/Math.max(.16,(e.speed??1)*(e.eventMultiplier??1));}
promoteBikeLanes(count,speed=1.4){const visualIds=[...new Set(this.rng.shuffle(this.visualEdges.filter((e)=>e.roadClass!=='connector')).slice(0,count).map((e)=>e.id))];for(const e of this.edges)if(visualIds.includes(e.visualId)){e.speed=Math.max(e.speed,speed);e.bikeLane=true;}for(const e of this.visualEdges)if(visualIds.includes(e.id))e.bikeLane=true;}
addCourier(){if(this.courierSerial>=COURIER_NAMES.length)return false;const depot=this.nodeById(this.depotNodeId),index=this.courierSerial++,personality=this.rng.pick(PERSONALITIES),experience=weightedPick(this.rng,EXPERIENCE,(e)=>[0,3.1,4.1,2.8,1.2][e.level]),homeDistrict=this.rng.pick(this.districts).id;this.couriers.push({id:`c${index}`,name:COURIER_NAMES[index],color:COURIER_COLORS[index],personality,experience,homeDistrict,nodeId:depot.id,x:depot.x+(index-1)*8,y:depot.y+(index-1)*6,path:[],pathIndex:0,targetNodeId:null,deliveryId:null,phase:'idle',baseSpeed:64+this.rng.float(-3,5),decisionAt:this.elapsed+this.rng.float(.35,1.1),deliberation:null,lastDecision:'Radio on · listening',completed:0,radioOn:true,fatigue:this.rng.float(.05,.14),breakUntil:null,breaks:0});return true;}
availableRiders(){return this.couriers.filter((c)=>c.phase==='idle'&&c.radioOn);}
activeDeliveries(){return this.deliveries.filter((d)=>d.status==='waiting'||d.status==='claimed');}
calledDeliveries(){return this.deliveries.filter((d)=>d.status==='waiting'&&d.called);}
calledCount(){return this.calledDeliveries().length;}
radioCost(d){return d?.called?(RADIO_CHANNELS[d.channel]?.cost??1):0;}
radioUsed(){return this.calledDeliveries().reduce((s,d)=>s+this.radioCost(d),0);}
urgency(d){const total=Math.max(1,d.deadlineAt-d.createdAt);return Math.max(0,Math.min(1,(d.deadlineAt-this.elapsed)/total));}
weightedDeliveryType(){const weights=this.runContract.typeWeights??{};return weightedPick(this.rng,Object.entries(DELIVERY_TYPES),(entry)=>entry[1].weight*(weights[entry[0]]??1))[0];}
randomAddress(excludeId=null){const pool=this.addressNodes.filter((n)=>n.id!==excludeId&&n.id!==this.depotNodeId);return this.rng.pick(pool);}
randomTrip(){const min=this.runContract.minTrip??120,max=this.runContract.maxTrip??1000;for(let attempt=0;attempt<22;attempt++){const pickup=this.randomAddress(),dropoff=this.randomAddress(pickup?.id);if(!pickup||!dropoff)continue;const path=this.routeBetween(pickup.id,dropoff.id);if(!path.length)continue;const d=this.routeDistance(path);if(d>=min&&d<=max)return{pickup,dropoff,path,distance:d};}const pickup=this.randomAddress(),dropoff=this.randomAddress(pickup?.id),path=this.routeBetween(pickup.id,dropoff.id);return pickup&&dropoff&&path.length?{pickup,dropoff,path,distance:this.routeDistance(path)}:null;}
spawnDelivery(){if(this.activeDeliveries().length>=34)return false;const trip=this.randomTrip();if(!trip)return false;const typeKey=this.weightedDeliveryType(),type=DELIVERY_TYPES[typeKey],distanceFactor=.82+trip.distance/900,deadline=type.baseDeadline*this.modifiers.deadline*distanceFactor/(1+(this.wave-1)*.014),id=`d${this.deliverySerial++}`,reward=Math.round((type.reward+trip.distance/92)*this.modifiers.reward);this.deliveries.push({id,type:typeKey,pickupId:trip.pickup.id,dropoffId:trip.dropoff.id,pickupAddress:trip.pickup.addressLabel,dropoffAddress:trip.dropoff.addressLabel,pickupPostcode:trip.pickup.postcode,dropoffPostcode:trip.dropoff.postcode,pickupDistrict:trip.pickup.districtId,dropoffDistrict:trip.dropoff.districtId,createdAt:this.elapsed,deadlineAt:this.elapsed+deadline,reward,status:'waiting',called:false,channel:null,courierId:null,pickedUp:false,firstCalledAt:null,claimedAt:null,edgesTraversed:[],callHistory:[],plannedDistance:trip.distance,plannedStreets:this.routeStreets(trip.path)});this.runStats.peakActive=Math.max(this.runStats.peakActive,this.activeDeliveries().length);return true;}
}
