export const DELIVERY_TYPES={food:{label:'Food',glyph:'▲',color:'#ff5f87',baseDeadline:66,reward:10},parcel:{label:'Parcel',glyph:'●',color:'#ffb02e',baseDeadline:90,reward:12},document:{label:'Docs',glyph:'■',color:'#4dd8d0',baseDeadline:72,reward:15},medical:{label:'Medical',glyph:'✚',color:'#ff435f',baseDeadline:54,reward:24},grocery:{label:'Grocery',glyph:'⬢',color:'#9edc4a',baseDeadline:96,reward:13},fragile:{label:'Fragile',glyph:'◆',color:'#b879ed',baseDeadline:82,reward:18}};
export const RADIO_CHANNELS={open:{id:'open',label:'Open',short:'OPEN',cost:1,color:'#62c9ef'},priority:{id:'priority',label:'Priority',short:'PRIORITY',cost:2,color:'#f2c14e'},local:{id:'local',label:'Local',short:'LOCAL',cost:1,color:'#57d6b8'}};
export const PERSONALITIES=[{id:'sprinter',title:'Sprinter',icon:'⚡',desc:'Close and urgent work.',weights:{distance:1.55,urgency:1.25,reward:.45,landmark:.15}},{id:'earner',title:'Earner',icon:'€',desc:'High-paying work.',weights:{distance:.7,urgency:.7,reward:1.7,landmark:.15}},{id:'guardian',title:'Guardian',icon:'✚',desc:'Urgent and medical work.',weights:{distance:.75,urgency:1.75,reward:.45,medical:1.35,landmark:.1}},{id:'local',title:'Local',icon:'⌂',desc:'Nearby familiar pickups.',weights:{distance:1.9,urgency:.7,reward:.35,sameDistrict:.9,landmark:.1}},{id:'tourer',title:'Tourer',icon:'◎',desc:'Landmarks and longer rides.',weights:{distance:.25,urgency:.7,reward:.75,landmark:1.35,longRide:.85}},{id:'steady',title:'Steady',icon:'≋',desc:'Balanced choices.',weights:{distance:1.05,urgency:1.05,reward:.95,landmark:.25}}];
export const EXPERIENCE=[{level:1,title:'Rookie',speed:.94,think:1.45,noise:.34},{level:2,title:'Regular',speed:1,think:1.18,noise:.22},{level:3,title:'Experienced',speed:1.06,think:.94,noise:.13},{level:4,title:'Veteran',speed:1.11,think:.78,noise:.07}];
export const COURIER_NAMES=['Kira','Mauro','Brian','Sam','Michail','Zorro'];
export const COURIER_COLORS=['#52c7ff','#ff6b8b','#9bd65c','#f5c24f','#aa8cff','#ff8759'];
export const RUN_TRAITS=[{id:'express',title:'Express Berlin',desc:'Tighter windows; better payouts.',apply(g){g.modifiers.deadline*=.91;g.modifiers.reward*=1.18;}},{id:'green-wave',title:'Green Wave',desc:'Several real corridors start as fast bike links.',apply(g){g.promoteBikeLanes(9,1.34);}},{id:'tourist-saturday',title:'Tourist Saturday',desc:'More jobs touch major landmarks.',apply(g){g.modifiers.landmarkBias=.48;g.modifiers.reward*=1.06;}},{id:'rain-shift',title:'Rain Shift',desc:'Riders move slower; clients tip more.',apply(g){g.modifiers.speed*=.92;g.modifiers.reward*=1.2;}}];
export const UPGRADES=[{id:'radio',title:'Radio Bandwidth',desc:'+1 broadcast bandwidth.',apply(g){g.radioSlots+=1;}},{id:'rider',title:'Extra Rider',desc:'The next named rider joins the team.',apply(g){g.addCourier();}},{id:'briefing',title:'Team Briefing',desc:'Faster, less noisy rider decisions.',apply(g){g.modifiers.teamSkill*=1.2;}},{id:'speed',title:'Street Legs',desc:'All active riders move 10% faster.',apply(g){g.modifiers.speed*=1.1;}},{id:'grace',title:'Client Buffer',desc:'New deadlines are 14% longer.',apply(g){g.modifiers.deadline*=1.14;}},{id:'bikeLane',title:'Bike-Lane Grant',desc:'Seven street segments become fast corridors.',apply(g){g.promoteBikeLanes(7,1.45);}},{id:'goodwill',title:'Local Goodwill',desc:'+18 reputation now.',apply(g){g.reputation=Math.min(100,g.reputation+18);}}];
export const ROAD_EVENT_TYPES=[{id:'roadworks',title:'ROADWORKS',factor:.5,duration:[30,45],forecast:'A street segment will narrow soon.'},{id:'demo',title:'DEMONSTRATION',factor:.58,duration:[24,38],forecast:'Crowds are expected on a central corridor.'},{id:'bridge',title:'BRIDGE SQUEEZE',factor:.45,duration:[24,38],forecast:'A Spree crossing will slow down.',bridgeOnly:true}];
export const edgeKey=(a,b)=>[a,b].sort().join('|');
export function weightedPick(rng,items,weightFn){if(!items.length)return undefined;const weights=items.map((item)=>Math.max(0,Number(weightFn(item))||0)),total=weights.reduce((a,b)=>a+b,0);if(total<=0)return rng.pick(items);let roll=rng.float(0,total);for(let i=0;i<items.length;i+=1){roll-=weights[i];if(roll<=0)return items[i];}return items.at(-1);}
