import { Game,DELIVERY_TYPES,RADIO_CHANNELS } from './game.js';
import { createSeed } from './rng.js';
import { Renderer } from './render.js';
const FIXED_STEP=1/60,$=(s)=>document.querySelector(s),canvas=$('#game-canvas');
const stats={score:$('#score'),cash:$('#cash'),rep:$('#rep'),wave:$('#wave'),seed:$('#seed'),active:$('#active-count'),called:$('#called-count'),slots:$('#radio-slots'),trait:$('#trait'),traitDesc:$('#trait-desc'),contract:$('#contract'),contractDesc:$('#contract-desc')};
const deliveriesEl=$('#deliveries'),couriersEl=$('#couriers'),goalsEl=$('#goals'),noticeEl=$('#notice'),eventChip=$('#event-chip'),eventState=$('#event-state'),eventTitle=$('#event-title'),eventDetail=$('#event-detail'),eventTime=$('#event-time');
const controlsOverview=$('#controls-overview'),upgradeModal=$('#upgrade-modal'),upgradeChoices=$('#upgrade-choices'),gameoverModal=$('#gameover-modal'),summaryEl=$('#run-summary'),bestEl=$('#best-score'),reviewMetrics=$('#review-metrics'),reviewAdvice=$('#review-advice');
const jobEls=new Map(),riderEls=new Map(),goalEls=new Map();let game,renderer,lastTime=performance.now(),accumulator=0,lastUiRender=0,shownUpgradeAt=-1,drag=null,suppressCanvasClick=false,overviewPauseWas=false;
const setText=(el,value)=>{const text=String(value??'');if(el&&el.textContent!==text)el.textContent=text;};
function openDialog(dialog){dialog.hidden=false;if(dialog.open)return;if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','');}
function closeDialog(dialog){if(!dialog)return;if(dialog.open&&typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open');dialog.hidden=true;}
function readLocal(key,fallback=''){try{return localStorage.getItem(key)??fallback;}catch{return fallback;}}
function writeLocal(key,value){try{localStorage.setItem(key,String(value));}catch{}}
function currentSeed(){const raw=new URLSearchParams(location.search).get('seed');if(!raw)return createSeed();const cleaned=raw.toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,32);return cleaned||createSeed();}
function syncUrl(seed){const url=new URL(location.href);url.searchParams.set('seed',seed);history.replaceState(null,'',url);}
function formatTime(seconds){const value=Math.max(0,Math.ceil(seconds));return `${Math.floor(value/60)}:${String(value%60).padStart(2,'0')}`;}
function formatKm(world){return `${Math.max(.1,world/100).toFixed(1)} km`;}
function clearDynamic(){for(const el of jobEls.values())el.remove();for(const el of riderEls.values())el.remove();for(const el of goalEls.values())el.remove();jobEls.clear();riderEls.clear();goalEls.clear();}
function start(seed=currentSeed()){game=new Game({seed});renderer=new Renderer(canvas,game);lastTime=performance.now();accumulator=0;lastUiRender=0;shownUpgradeAt=-1;clearDynamic();closeDialog(upgradeModal);closeDialog(gameoverModal);syncUrl(seed);renderUI(true);const first=readLocal('bike.controls.v4')!=='1';if(first)setControls(true,true);else controlsOverview.hidden=true;}
function createJobElement(d){const el=document.createElement('article');el.className='job-card';el.dataset.delivery=d.id;el.innerHTML=`<button class="job-select" data-select><span class="job-glyph"></span><span class="job-copy"><span class="job-top"><strong class="job-id"></strong><em class="job-type"></em><time class="job-time"></time></span><span class="address pickup"></span><span class="address dropoff"></span><span class="job-meta"></span></span></button><div class="channel-actions"><button data-channel="open">OPEN<small>1</small></button><button data-channel="priority">PRIORITY<small>2</small></button><button data-channel="local">LOCAL<small>1</small></button><button data-channel="off">OFF</button><span class="taken-note" hidden>RIDER COMMITTED</span></div>`;deliveriesEl.append(el);jobEls.set(d.id,el);return el;}
function updateJobElement(el,d){const type=DELIVERY_TYPES[d.type],remaining=d.deadlineAt-game.elapsed,claimed=d.status==='claimed',nearest=game.nearestIdleDistance(d),channel=d.called?d.channel:'off';el.style.setProperty('--type',type.color);el.dataset.channel=channel;el.dataset.claimed=String(claimed);el.classList.toggle('selected',game.selectedDeliveryId===d.id);setText(el.querySelector('.job-glyph'),d.pickedUp?'◎':type.glyph);setText(el.querySelector('.job-id'),d.id.toUpperCase());setText(el.querySelector('.job-type'),type.label);setText(el.querySelector('.pickup'),`P  ${d.pickupAddress}`);setText(el.querySelector('.dropoff'),`D  ${d.dropoffAddress}`);const state=claimed?`${game.courierById(d.courierId)?.name??'Rider'} committed`:d.called?`${RADIO_CHANNELS[d.channel].short} radio`:nearest==null?'no free rider':`${formatKm(nearest)} to nearest rider`;setText(el.querySelector('.job-meta'),`${formatKm(d.plannedDistance)} · ${state} · €${d.reward}`);const time=el.querySelector('.job-time');setText(time,formatTime(remaining));time.classList.toggle('urgent',remaining<18);for(const button of el.querySelectorAll('[data-channel]')){const id=button.dataset.channel;button.hidden=claimed||(id==='off'&&!d.called);button.classList.toggle('active',d.called&&d.channel===id);}el.querySelector('.taken-note').hidden=!claimed;}
function syncJobs(){const active=game.activeDeliveries().sort((a,b)=>{if(a.status!==b.status)return a.status==='waiting'?-1:1;if(a.called!==b.called)return a.called?-1:1;return a.deadlineAt-b.deadlineAt;}).slice(0,22),ids=new Set(active.map((d)=>d.id));for(const[id,el]of jobEls)if(!ids.has(id)){el.remove();jobEls.delete(id);}for(const d of active){const el=jobEls.get(d.id)??createJobElement(d);updateJobElement(el,d);deliveriesEl.append(el);}}
function createRiderElement(c){const el=document.createElement('button');el.className='rider-card';el.dataset.courier=c.id;el.innerHTML=`<span class="rider-icon"></span><span class="rider-copy"><span class="rider-name"></span><span class="rider-profile"></span><span class="rider-decision"></span><span class="rider-location"></span></span><span class="rider-status"></span><span class="fatigue"><i></i></span>`;couriersEl.append(el);riderEls.set(c.id,el);return el;}
function riderLocation(c){const n=game.nodeById(c.nodeId);if(n?.addressLabel)return n.addressLabel;if(c.path?.length>c.pathIndex){const next=game.nodeById(c.path[c.pathIndex]),edge=game.edgeByIds(c.nodeId,next?.id);if(edge?.streetName)return edge.streetName;}return game.districts.find((d)=>d.id===n?.districtId)?.name??'Berlin';}
function updateRiderElement(el,c){const onBreak=c.phase==='break'||!c.radioOn,busy=c.phase==='pickup'||c.phase==='dropoff',thinking=Boolean(c.deliberation),predicted=game.predictCall(c);el.style.setProperty('--rider',c.color);el.dataset.break=String(onBreak);el.classList.toggle('selected',game.selectedCourierId===c.id);setText(el.querySelector('.rider-icon'),onBreak?'Ⅱ':c.experience.level);setText(el.querySelector('.rider-name'),c.name);setText(el.querySelector('.rider-profile'),`${c.personality.icon} ${c.personality.title} · ${c.experience.title}`);setText(el.querySelector('.rider-location'),riderLocation(c));let decision=c.lastDecision,status='LISTENING',statusClass='listening';if(onBreak){decision=`Radio off · back ${formatTime(game.breakRemaining(c))}`;status='BREAK';statusClass='break';}else if(busy){const d=game.deliveryById(c.deliveryId);decision=c.phase==='pickup'?`To ${d?.pickupAddress??'pickup'}`:`To ${d?.dropoffAddress??'drop'}`;status='RIDING';statusClass='busy';}else if(thinking){const d=game.deliveryById(c.deliberation.deliveryId);decision=`Considering ${d?.id.toUpperCase()??'job'} · ${Math.round(game.deliberationProgress(c)*100)}%`;status='THINKING';statusClass='thinking';}else if(predicted)decision=`Leaning ${predicted.delivery.id.toUpperCase()} · ${c.personality.title.toLowerCase()}`;setText(el.querySelector('.rider-decision'),decision);const badge=el.querySelector('.rider-status');setText(badge,status);badge.className=`rider-status ${statusClass}`;el.querySelector('.fatigue i').style.width=`${Math.round(c.fatigue*100)}%`;}
function syncRiders(){const ids=new Set(game.couriers.map((c)=>c.id));for(const[id,el]of riderEls)if(!ids.has(id)){el.remove();riderEls.delete(id);}for(const c of game.couriers){const el=riderEls.get(c.id)??createRiderElement(c);updateRiderElement(el,c);couriersEl.append(el);}}
function createGoalElement(g){const el=document.createElement('article');el.className='goal-card';el.dataset.goal=g.id;el.innerHTML='<div><strong></strong><span></span></div><p></p><div class="goal-bar"><i></i></div><small></small>';goalsEl.append(el);goalEls.set(g.id,el);return el;}
function syncGoals(){for(const g of game.goals){const el=goalEls.get(g.id)??createGoalElement(g);el.classList.toggle('complete',g.complete);setText(el.querySelector('strong'),`${g.complete?'✓ ':''}${g.label}`);setText(el.querySelector('div span'),`${g.progress}/${g.target}`);setText(el.querySelector('p'),g.detail);el.querySelector('.goal-bar i').style.width=`${Math.min(100,g.progress/g.target*100)}%`;setText(el.querySelector('small'),g.complete?'complete':`€${g.reward} + REP`);}}
function renderEvent(){const ev=game.currentEvent;if(!ev){eventChip.hidden=true;return;}eventChip.hidden=false;eventChip.dataset.state=ev.state;setText(eventState,ev.state==='active'?'ACTIVE':'FORECAST');setText(eventTitle,`${ev.title} · ${ev.place}`);setText(eventDetail,ev.state==='active'?'Street is slower; riders reroute at intersections.':ev.detail);setText(eventTime,ev.state==='active'?`${formatTime(ev.endsAt-game.elapsed)} left`:`in ${formatTime(ev.startsAt-game.elapsed)}`);}
function renderUI(force=false){setText(stats.score,Math.round(game.score).toLocaleString());setText(stats.cash,`€${game.cash}`);setText(stats.rep,`${Math.round(game.reputation)}%`);stats.rep.dataset.level=game.reputation<35?'danger':game.reputation<65?'warn':'good';setText(stats.wave,game.wave);setText(stats.seed,game.seed);setText(stats.active,game.activeDeliveries().length);setText(stats.called,game.radioUsed());setText(stats.slots,game.radioSlots);setText(stats.trait,game.runTrait.title);setText(stats.traitDesc,game.runTrait.desc);setText(stats.contract,game.runContract.title);setText(stats.contractDesc,game.runContract.desc);setText(noticeEl,game.elapsed<=game.noticeUntil?game.notice:'');setText($('#pause'),game.paused?'▶':'Ⅱ');document.querySelectorAll('[data-speed]').forEach((b)=>b.classList.toggle('active',!game.paused&&Number(b.dataset.speed)===game.speed));renderEvent();syncJobs();syncRiders();syncGoals();if(force)updateZoomLabel();}
function showUpgrade(){if(!game.upgradePending||shownUpgradeAt===game.nextUpgradeAt)return;shownUpgradeAt=game.nextUpgradeAt;upgradeChoices.replaceChildren();for(const u of game.getUpgradeChoices()){const button=document.createElement('button');button.dataset.upgrade=u.id;button.innerHTML=`<strong>${u.title}</strong><span>${u.desc}</span>`;upgradeChoices.append(button);}openDialog(upgradeModal);}
function showGameOver(){const s=game.summary(),best=Math.max(Number(readLocal('bike.bestScore','0'))||0,s.score);writeLocal('bike.bestScore',best);setText(bestEl,best.toLocaleString());summaryEl.replaceChildren();for(const[value,label]of[[s.score.toLocaleString(),'Score'],[s.completed,'Delivered'],[s.failed,'Missed'],[`${s.goals}/${game.goals.length}`,'Goals'],[s.review.breaks,'Breaks'],[s.seed,'Seed']]){const box=document.createElement('div');box.innerHTML=`<strong>${value}</strong><span>${label}</span>`;summaryEl.append(box);}reviewMetrics.replaceChildren();for(const[value,label]of[[s.review.neverCalled,'Never called'],[s.review.calledUnclaimed,'No taker'],[s.review.claimedLate,'Accepted late'],[s.review.radioDenied,'Radio blocked']]){const box=document.createElement('div');box.innerHTML=`<strong>${value}</strong><span>${label}</span>`;reviewMetrics.append(box);}reviewAdvice.replaceChildren();const top=document.createElement('p');top.innerHTML=`<b>Top rider:</b> ${s.review.topRider}`;reviewAdvice.append(top);for(const advice of s.review.advice){const p=document.createElement('p');p.textContent=advice;reviewAdvice.append(p);}openDialog(gameoverModal);}
function frame(now){const frameDt=Math.min(.25,(now-lastTime)/1000);lastTime=now;accumulator+=frameDt;let steps=0;while(accumulator>=FIXED_STEP&&steps<15){game.update(FIXED_STEP);accumulator-=FIXED_STEP;steps++;}if(steps===15)accumulator=0;renderer.draw();if(now-lastUiRender>=140){renderUI();lastUiRender=now;}showUpgrade();if(game.gameOver&&!gameoverModal.open)showGameOver();requestAnimationFrame(frame);}
function updateZoomLabel(){setText($('#zoom-label'),`${Math.round(renderer.zoom*100)}%`);}
function inspectDelivery(id){const d=game.deliveryById(id);if(d&&!d.plannedPath)d.plannedPath=game.routeBetween(d.pickupId,d.dropoffId);game.selectDelivery(id);renderUI();}
canvas.addEventListener('wheel',(event)=>{event.preventDefault();const rect=canvas.getBoundingClientRect();renderer.zoomAt(event.clientX-rect.left,event.clientY-rect.top,event.deltaY<0?1.14:.88);updateZoomLabel();},{passive:false});
canvas.addEventListener('pointerdown',(event)=>{if(event.button!==0)return;drag={id:event.pointerId,x:event.clientX,y:event.clientY,startX:event.clientX,startY:event.clientY};canvas.setPointerCapture(event.pointerId);canvas.classList.add('dragging');});
canvas.addEventListener('pointermove',(event)=>{if(!drag||drag.id!==event.pointerId)return;const dx=event.clientX-drag.x,dy=event.clientY-drag.y;drag.x=event.clientX;drag.y=event.clientY;if(Math.hypot(event.clientX-drag.startX,event.clientY-drag.startY)>5)suppressCanvasClick=true;renderer.pan(dx,dy);});
canvas.addEventListener('pointerup',(event)=>{if(!drag||drag.id!==event.pointerId)return;drag=null;canvas.releasePointerCapture(event.pointerId);canvas.classList.remove('dragging');setTimeout(()=>{suppressCanvasClick=false;},0);});
canvas.addEventListener('click',(event)=>{if(suppressCanvasClick)return;const rect=canvas.getBoundingClientRect(),point=renderer.screenToWorld(event.clientX-rect.left,event.clientY-rect.top),entity=game.nearestEntity(point.x,point.y,24/renderer.scale);if(!entity)return;if(entity.type==='delivery')inspectDelivery(entity.id);if(entity.type==='courier'){game.selectCourier(entity.id);renderUI();}});
deliveriesEl.addEventListener('click',(event)=>{const card=event.target.closest('[data-delivery]');if(!card)return;const d=game.deliveryById(card.dataset.delivery);if(!d)return;const channel=event.target.closest('[data-channel]');if(channel){game.setChannel(d.id,channel.dataset.channel);renderUI();return;}inspectDelivery(d.id);});
couriersEl.addEventListener('click',(event)=>{const card=event.target.closest('[data-courier]');if(card){game.selectCourier(card.dataset.courier);renderUI();}});
upgradeChoices.addEventListener('click',(event)=>{const button=event.target.closest('[data-upgrade]');if(button&&game.applyUpgrade(button.dataset.upgrade)){closeDialog(upgradeModal);renderUI(true);}});
$('#pause').addEventListener('click',()=>{game.paused=!game.paused;renderUI();});document.querySelectorAll('[data-speed]').forEach((button)=>button.addEventListener('click',()=>{game.speed=Number(button.dataset.speed);game.paused=false;renderUI();}));
$('#new-run').addEventListener('click',()=>start(createSeed()));$('#same-seed').addEventListener('click',()=>start(game.seed));$('#random-seed').addEventListener('click',()=>start(createSeed()));
$('#zoom-in').addEventListener('click',()=>{renderer.zoomAt(renderer.viewWidth/2,renderer.viewHeight/2,1.18);updateZoomLabel();});$('#zoom-out').addEventListener('click',()=>{renderer.zoomAt(renderer.viewWidth/2,renderer.viewHeight/2,.84);updateZoomLabel();});$('#zoom-reset').addEventListener('click',()=>{renderer.resetView();updateZoomLabel();});
function setControls(show,fromFirstRun=false){if(show){overviewPauseWas=fromFirstRun?false:game.paused;game.paused=true;controlsOverview.hidden=false;}else{controlsOverview.hidden=true;writeLocal('bike.controls.v4','1');game.paused=overviewPauseWas;}$('#controls-toggle').setAttribute('aria-expanded',String(show));renderUI();}
$('#controls-toggle').addEventListener('click',()=>setControls(controlsOverview.hidden));$('#controls-close').addEventListener('click',()=>setControls(false));$('#controls-done').addEventListener('click',()=>setControls(false));
window.addEventListener('keydown',(event)=>{if(upgradeModal.open||gameoverModal.open)return;if(event.key==='?'||event.key==='h'||event.key==='H'){event.preventDefault();setControls(controlsOverview.hidden);return;}if(!controlsOverview.hidden){if(event.key==='Escape')setControls(false);return;}if(event.key===' '){event.preventDefault();game.paused=!game.paused;renderUI();}if(event.key==='1'){game.speed=1;game.paused=false;}if(event.key==='2'){game.speed=2;game.paused=false;}if(event.key==='3'){game.speed=4;game.paused=false;}if(event.key==='0'){renderer.resetView();updateZoomLabel();}if(event.key==='Escape'){game.selectedDeliveryId=null;game.selectedCourierId=null;renderUI();}});
window.addEventListener('resize',()=>renderer.resize());start();requestAnimationFrame(frame);
