import { DELIVERY_TYPES, RADIO_CHANNELS } from './game.js';

export class Renderer {
  constructor(canvas,game){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.game=game;this.dpr=Math.min(2,window.devicePixelRatio||1);this.resize();}
  resize(){const rect=this.canvas.getBoundingClientRect(),w=Math.max(320,rect.width),h=Math.max(420,rect.height);this.canvas.width=Math.round(w*this.dpr);this.canvas.height=Math.round(h*this.dpr);this.ctx.setTransform(this.dpr,0,0,this.dpr,0,0);this.viewWidth=w;this.viewHeight=h;const pad=26;this.scale=Math.min((w-pad*2)/this.game.width,(h-pad*2)/this.game.height);this.offsetX=(w-this.game.width*this.scale)/2;this.offsetY=(h-this.game.height*this.scale)/2;}
  worldToScreen(x,y){return{x:this.offsetX+x*this.scale,y:this.offsetY+y*this.scale};}
  screenToWorld(x,y){return{x:(x-this.offsetX)/this.scale,y:(y-this.offsetY)/this.scale};}
  draw(){const ctx=this.ctx;ctx.clearRect(0,0,this.viewWidth,this.viewHeight);this.drawBackdrop();ctx.save();ctx.translate(this.offsetX,this.offsetY);ctx.scale(this.scale,this.scale);this.drawDistricts();this.drawParks();this.drawRiver();this.drawEdges();this.drawLandmarks();this.drawAttention();this.drawRoutes();this.drawDeliveries();this.drawCouriers();ctx.restore();}
  drawBackdrop(){const ctx=this.ctx,g=ctx.createLinearGradient(0,0,this.viewWidth,this.viewHeight);g.addColorStop(0,'#07111f');g.addColorStop(1,'#10172b');ctx.fillStyle=g;ctx.fillRect(0,0,this.viewWidth,this.viewHeight);ctx.globalAlpha=.1;ctx.fillStyle='#fff';for(let x=18;x<this.viewWidth;x+=34)for(let y=18;y<this.viewHeight;y+=34)ctx.fillRect(x,y,1,1);ctx.globalAlpha=1;}
  polygon(points){const ctx=this.ctx;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();}
  drawDistricts(){const ctx=this.ctx;for(const d of this.game.districts){this.polygon(d.polygon);ctx.fillStyle=`${d.color}12`;ctx.fill();ctx.strokeStyle=`${d.color}40`;ctx.lineWidth=2;ctx.setLineDash([9,10]);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=`${d.color}aa`;ctx.font='800 14px system-ui,sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(d.name.toUpperCase(),d.center[0],d.center[1]);}}
  drawParks(){const ctx=this.ctx;for(const p of this.game.parks){this.polygon(p.polygon);ctx.fillStyle=`${p.color}1d`;ctx.fill();ctx.strokeStyle=`${p.color}58`;ctx.lineWidth=2;ctx.stroke();const cx=p.polygon.reduce((s,q)=>s+q[0],0)/p.polygon.length,cy=p.polygon.reduce((s,q)=>s+q[1],0)/p.polygon.length;ctx.fillStyle=`${p.color}9f`;ctx.font='700 12px system-ui';ctx.textAlign='center';ctx.fillText(p.name.toUpperCase(),cx,cy);}}
  drawRiver(){const ctx=this.ctx;ctx.beginPath();this.game.river.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.strokeStyle='#2aa8e7';ctx.lineWidth=18;ctx.globalAlpha=.18;ctx.lineCap='round';ctx.lineJoin='round';ctx.stroke();ctx.lineWidth=4;ctx.globalAlpha=.68;ctx.stroke();ctx.globalAlpha=1;}
  drawEdges(){const ctx=this.ctx,byId=new Map(this.game.nodes.map((n)=>[n.id,n])),event=this.game.currentEvent;ctx.lineCap='round';for(const e of this.game.edges){const a=byId.get(e.a),b=byId.get(e.b),affected=event?.edgeIds.includes(e.id);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);if(affected){ctx.strokeStyle=event.state==='active'?'#ff5a68':'#ffbd4a';ctx.lineWidth=event.state==='active'?8:6;ctx.globalAlpha=.85;ctx.setLineDash(event.state==='forecast'?[10,8]:[]);}else{ctx.strokeStyle=e.bikeLane?'#48f1bd':'#3e4c66';ctx.lineWidth=e.bikeLane?5:3;ctx.globalAlpha=e.bikeLane?.82:.58;ctx.setLineDash([]);}ctx.stroke();ctx.setLineDash([]);if(e.bridgeId&&!affected){ctx.strokeStyle='#67cfff';ctx.lineWidth=2;ctx.globalAlpha=.55;ctx.stroke();}}ctx.globalAlpha=1;}
  drawLandmarks(){const ctx=this.ctx;for(const l of this.game.landmarks){ctx.beginPath();ctx.arc(l.x,l.y,8,0,Math.PI*2);ctx.fillStyle='#0a1425';ctx.fill();ctx.strokeStyle='#e7f4ff';ctx.lineWidth=2.5;ctx.stroke();ctx.fillStyle='#f7fbff';ctx.font='800 12px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(l.glyph,l.x,l.y+.5);ctx.font='700 11px system-ui';ctx.textAlign='left';ctx.textBaseline='alphabetic';ctx.fillStyle='#d7e7f5';ctx.globalAlpha=.76;ctx.fillText(l.short,l.x+11,l.y-8);ctx.globalAlpha=1;}}
  drawAttention(){const ctx=this.ctx;for(const c of this.game.couriers){if(c.phase!=='idle')continue;const predicted=this.game.predictCall(c);if(!predicted)continue;const pickup=this.game.nodeById(predicted.delivery.pickupId),deliberating=Boolean(c.deliberation),progress=deliberating?this.game.deliberationProgress(c):0;ctx.beginPath();ctx.moveTo(c.x,c.y);ctx.lineTo(pickup.x,pickup.y);ctx.strokeStyle=c.color;ctx.lineWidth=deliberating?3:2;ctx.globalAlpha=deliberating?.28+.42*progress:.16;ctx.setLineDash(deliberating?[5,6]:[3,9]);ctx.stroke();ctx.setLineDash([]);if(deliberating){ctx.beginPath();ctx.arc(pickup.x,pickup.y,22+progress*5,0,Math.PI*2);ctx.strokeStyle=c.color;ctx.lineWidth=2;ctx.globalAlpha=.18+.26*progress;ctx.stroke();}ctx.globalAlpha=1;}}
  drawRoutes(){const ctx=this.ctx,byId=new Map(this.game.nodes.map((n)=>[n.id,n]));for(const c of this.game.couriers){if(c.path.length<2)continue;ctx.beginPath();ctx.moveTo(c.x,c.y);for(let i=c.pathIndex;i<c.path.length;i++){const n=byId.get(c.path[i]);if(n)ctx.lineTo(n.x,n.y);}ctx.strokeStyle=c.color;ctx.lineWidth=5;ctx.globalAlpha=.5;ctx.setLineDash([8,8]);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1;}}
  drawDeliveries(){const ctx=this.ctx,time=performance.now()/1000;for(const d of this.game.activeDeliveries()){const pickup=this.game.nodeById(d.pickupId),dropoff=this.game.nodeById(d.dropoffId),node=d.pickedUp?dropoff:pickup,type=DELIVERY_TYPES[d.type],urgency=this.game.urgency(d),selected=this.game.selectedDeliveryId===d.id,called=d.called,claimed=d.status==='claimed',channel=RADIO_CHANNELS[d.channel],channelColor=channel?.color??type.color;const pulse=urgency<.32?1+Math.sin(time*7)*.12:1,r=(selected?18:14)*pulse;ctx.beginPath();ctx.arc(node.x,node.y,r,0,Math.PI*2);ctx.fillStyle=claimed?'#101b2d':'#08111f';ctx.globalAlpha=d.status==='waiting'&&!called?.68:1;ctx.fill();ctx.strokeStyle=type.color;ctx.lineWidth=selected?6:called?4:3;ctx.stroke();ctx.globalAlpha=1;ctx.beginPath();ctx.arc(node.x,node.y,r+5,-Math.PI/2,-Math.PI/2+Math.PI*2*urgency);ctx.strokeStyle=urgency<.3?'#ff425e':'#eaf4ff';ctx.lineWidth=2.6;ctx.stroke();if(called&&d.status==='waiting'){const arcs=d.channel==='priority'?3:2;for(let i=0;i<arcs;i++){ctx.beginPath();const rr=r+10+i*7+Math.sin(time*5+i)*1.8;ctx.arc(node.x,node.y,rr,-.72,.72);ctx.strokeStyle=channelColor;ctx.lineWidth=2;ctx.globalAlpha=.56-i*.11;ctx.stroke();ctx.beginPath();ctx.arc(node.x,node.y,rr,Math.PI-.72,Math.PI+.72);ctx.stroke();}ctx.globalAlpha=1;ctx.beginPath();ctx.arc(node.x+r*.75,node.y-r*.75,7,0,Math.PI*2);ctx.fillStyle=channelColor;ctx.fill();ctx.fillStyle='#07111f';ctx.font='900 8px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(d.channel==='priority'?'!':d.channel==='local'?'L':'O',node.x+r*.75,node.y-r*.75+.4);}ctx.fillStyle=type.color;ctx.font='900 16px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(d.pickedUp?'◎':type.glyph,node.x,node.y+.5);ctx.font='800 10px ui-monospace,monospace';ctx.fillStyle='#fff';ctx.globalAlpha=.86;ctx.fillText(d.id.toUpperCase(),node.x,node.y+r+15);ctx.globalAlpha=1;}}
  drawCouriers(){const ctx=this.ctx,time=performance.now()/1000;for(const c of this.game.couriers){const selected=this.game.selectedCourierId===c.id,deliberating=Boolean(c.deliberation),progress=this.game.deliberationProgress(c);ctx.save();ctx.translate(c.x,c.y);if(c.phase==='idle'&&this.game.calledCount()>0){ctx.beginPath();ctx.arc(0,0,18,0,Math.PI*2);ctx.strokeStyle=c.color;ctx.lineWidth=2;ctx.globalAlpha=.18+Math.sin(time*3)*.05;ctx.stroke();ctx.globalAlpha=1;}if(deliberating){ctx.beginPath();ctx.arc(0,0,21,-Math.PI/2,-Math.PI/2+Math.PI*2*progress);ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.globalAlpha=.82;ctx.stroke();ctx.globalAlpha=1;}ctx.beginPath();ctx.arc(0,0,selected?15:12,0,Math.PI*2);ctx.fillStyle='#07101f';ctx.fill();ctx.strokeStyle=c.color;ctx.lineWidth=selected?6:4;ctx.stroke();ctx.fillStyle=c.color;ctx.beginPath();ctx.moveTo(0,-7);ctx.lineTo(7,6);ctx.lineTo(-7,6);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.font='900 8px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(c.experience.level,0,1);ctx.restore();}}
}
