// Native app acceptance, including the installed runtime when an executable is passed.
// node desktop/smoke.mjs [path/to/Send It.exe]
import {_electron as electron} from 'playwright';
import {expect} from 'playwright/test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url)),exe=process.argv[2]&&path.resolve(process.argv[2]);
const folder=path.join(root,'reports/desktop',exe?'packaged':'development');await mkdir(folder,{recursive:true});
const profile=await mkdtemp(path.join(tmpdir(),'send-it-app-test-'));
const env={...process.env,SEND_IT_DATA_DIR:profile};delete env.ELECTRON_RUN_AS_NODE;
const result={platform:process.platform,executable:exe??'development',checks:[],pageErrors:[],externalRequests:[],failedResources:[]};
let app,page;
async function launch(){
  app=await electron.launch({...(exe?{executablePath:exe}:{}),args:[...(exe?[]:[root]),'--host-resolver-rules=MAP * ~NOTFOUND'],cwd:root,env,timeout:60000});
  page=await app.firstWindow();page.setDefaultTimeout(30000);
  page.on('pageerror',e=>result.pageErrors.push(String(e)));
  page.on('request',r=>{if(/^https?:/.test(r.url()))result.externalRequests.push(r.url());});
  page.on('response',r=>{if(r.status()>=400)result.failedResources.push(r.url());});
  await expect(page.locator('#intro')).toBeVisible({timeout:60000});
}
const state=()=>page.evaluate(async()=>{const {Game}=await import('/src/game.js');const g=Game.lastInstance;return {tick:g.tick,seed:g.seed,cash:g.cash,completed:g.completed,positions:g.couriers.map(c=>[c.x,c.y,c.deliveryId]),jobs:g.deliveries.map(d=>[d.id,d.status]),wellbeing:g.couriers.map(c=>({state:c.wellbeing,offDuty:c.offDuty,view:g.riderWellbeing(c)}))};});
const dispatchState=()=>page.evaluate(async()=>{const {Game}=await import('/src/game.js');const g=Game.lastInstance;return {tick:g.tick,rng:g.rng,cash:g.cash,radio:g.radioUsed(),record:g.exportRun(),riders:g.couriers.map(c=>({x:c.x,y:c.y,phase:c.phase,fatigue:c.fatigue,deliveryId:c.deliveryId,deliberation:c.deliberation})),jobs:g.deliveries.map(d=>({id:d.id,status:d.status,called:d.called,channel:d.channel,courierId:d.courierId}))};});
async function broadcast(channel='open'){
  const button=page.locator(`[data-radio="${channel}"]`),before=await dispatchState();
  await button.click();
  await expect(page.locator('#broadcast-preview')).toBeVisible();
  await expect(page.locator('#forecast-rider')).not.toBeEmpty();
  await expect(page.locator('#forecast-detail')).not.toBeEmpty();
  await expect(page.locator('#forecast-consequences')).toBeVisible();
  const impact=await page.evaluate(async channel=>{const {Game}=await import('/src/game.js');const g=Game.lastInstance,d=g.deliveryById(g.selectedDeliveryId);return g.offerConsequences(g.broadcastForecast(d,channel).rider,d);},channel);
  await expect(page.locator('#forecast-consequences [data-impact=endurance]')).toHaveText(`${impact.endurance.current} → ${impact.endurance.projected} / ${impact.endurance.max}`);
  await page.locator('#forecast-route > summary').click();
  await expect(page.locator('#forecast-route .itinerary-stops li')).toHaveCount(impact.itinerary.length);
  assert.deepEqual(await dispatchState(),before,'first click must only preview the broadcast');
  result.checks.push('bundled offer preview shows the same projected endurance and real stop order without changing play');
  await button.click();
  await expect(page.locator('#radio-exchange')).toHaveAttribute('data-action','call');
  await expect(page.locator('#radio-lines [data-speaker=dispatcher]')).toContainText('You · dispatch');
}
try{
  await launch();
  result.runtime=await app.evaluate(({app})=>({version:app.getVersion(),packaged:app.isPackaged,electron:process.versions.electron}));
  assert.equal(result.runtime.version,JSON.parse(await readFile(path.join(root,'package.json'),'utf8')).version);
  if(exe)assert.equal(result.runtime.packaged,true);
  assert.ok(page.url().startsWith('sendit://app/'));
  assert.deepEqual(await page.evaluate(()=>[typeof require,typeof process]),['undefined','undefined']);
  result.checks.push('local custom origin loads with sandboxed renderer and no Node integration');
  await page.context().setOffline(true);
  await page.locator('#start-region').selectOption('spandau');await page.locator('[data-start=training]').click();
  const info=await page.evaluate(async()=>{const {Game}=await import('/src/game.js');const g=Game.lastInstance;return {nodes:g.nodes.length,city:g.cityData.metadata.id,rules:g.ruleset,start:g.startRegion};});
  assert.deepEqual(info,{nodes:198430,city:'berlin-city-v1-b81f2dddf012',rules:'berlin-dispatch-v8',start:'spandau'});
  assert.equal(await page.locator('#start-region option').count(),98);
  result.checks.push('complete Berlin and all locality choices load with networking offline');
  await page.locator('.rider-locate').first().click();
  while(await page.evaluate(async()=>{const {Renderer}=await import('/src/render.js');return Renderer.lastInstance.scale<2;}))await page.locator('#zoom-in').click();
  await expect.poll(()=>page.evaluate(async()=>{const {Renderer}=await import('/src/render.js');const b=Renderer.lastInstance.buildingDetails;return !!(b?.cache.size>0&&!b.pending.size&&!b.queue.length);}),{timeout:30000}).toBe(true);
  await expect(page.locator('#map-detail-status')).toContainText('Official building footprints');
  await page.screenshot({path:path.join(folder,'berlin.png')});
  await expect(page.locator('#team-list svg.bike-icon')).toHaveCount(3);
  for(let i=0;i<3;i++){
    const rider=page.locator('#team-list .rider').nth(i);
    await expect(rider.locator('.rider-preferences')).toBeVisible();
    const preference=await page.evaluate(async index=>{const {Game}=await import('/src/game.js');const g=Game.lastInstance;return g.riderProfile(g.couriers[index]).preferences;},i);
    assert.ok(preference);
    await expect(rider.locator('.rider-preferences')).toHaveText(preference);
    await expect(rider.locator('.rider-endurance')).toContainText(/\d+\s*\/\s*\d+/);
    await expect(rider.locator('.rider-capacity')).toContainText(/\d+(?:\.\d+)?\s*\/\s*\d+(?:\.\d+)?\s*kg/);
    const wellbeing=await page.evaluate(async index=>{const {Game}=await import('/src/game.js');const g=Game.lastInstance;return g.riderWellbeing(g.couriers[index]);},i);
    await expect(rider.locator('.rider-satisfaction')).toContainText(`${wellbeing.satisfaction} / ${wellbeing.max}`);
    await expect(rider.locator('.rider-waiting')).toContainText('Waiting for first tour');
    await expect(rider).toHaveAttribute('data-wellbeing',wellbeing.band);
  }
  result.checks.push('building detail, distinct bikes, rider preferences and current/max resources render offline');
  const beforeWellbeing=await state();
  await page.locator('.wellbeing-toggle').first().click();
  await expect(page.locator('#rider-wellbeing-dialog')).toBeVisible();
  await expect(page.locator('#rider-wellbeing-dialog')).toContainText('70');
  await expect(page.locator('#rider-wellbeing-dialog')).toContainText('25');
  await expect(page.locator('.wellbeing-detail')).not.toBeEmpty();
  await page.locator('#close-rider-wellbeing').click();
  assert.deepEqual(await state(),beforeWellbeing,'inspecting satisfaction ranges must not change rider state');
  result.checks.push('rider cards show first-tour waiting, satisfaction and inspectable consequences without advancing time');
  const before=await state();
  await page.locator('#desk-menu > summary').click();
  await page.locator('#open-sound-studio').click();
  for(const rider of ['Kira','Mauro','Brian'])await page.locator(`[data-listen=${rider}]`).click();
  for(let i=0;i<4;i++)await page.locator(`[data-rhythm="${i}"]`).click();
  assert.equal(await page.evaluate(async()=>{const {DeskScore}=await import('/src/playtest-score.js');return DeskScore.lastInstance.ctx.state;}),'running');
  await page.locator('#studio-toggle').click();
  assert.equal(await page.evaluate(async()=>{const {DeskScore}=await import('/src/playtest-score.js');return DeskScore.lastInstance.voices.size;}),0);
  await page.locator('#close-sound').click();assert.deepEqual(await state(),before);
  result.checks.push('three rider themes, four task rhythms and exact mute work without changing simulation');
  await page.locator('.job-select').first().click();await page.locator('#offer-options summary').click();await page.locator('#client-call').click();
  await expect(page.locator('#client-call-detail')).toContainText('fee reduced');
  const preferenceBefore=await state();
  await page.locator('#preferred-rider').selectOption('c0');
  assert.deepEqual(await state(),preferenceBefore,'a preferred rider remains an invitation, not an assignment');
  assert.equal(await page.evaluate(async()=>{const {Game}=await import('/src/game.js');return Game.lastInstance.actions.at(-1).type;}),'prefer');
  await broadcast();
  assert.equal(await page.evaluate(async()=>{const {Game}=await import('/src/game.js');return Game.lastInstance.deliveries[0].courierId;}),null);
  result.checks.push('rider preference and read-only first-click forecast preserve autonomy until the clock runs');
  await page.locator('#pause').click();
  await expect(page.locator('[data-job=d0] .job-status')).toContainText('is on it',{timeout:12000});
  await expect(page.locator('#delivery-receipt')).toBeVisible({timeout:45000});
  await page.locator('#pause').click();
  result.checks.push('client tradeoff, autonomous acceptance and real-time collection/delivery complete offline');
  const delivered=await page.evaluate(async()=>{const {Game}=await import('/src/game.js');const g=Game.lastInstance,d=g.deliveries.find(d=>d.status==='completed'),c=g.courierById(d.courierId);return {riderId:c.id,wellbeing:g.riderWellbeing(c)};});
  assert.ok(delivered.wellbeing.lastTourAgo>=0);
  assert.notEqual(delivered.wellbeing.lastTourEndedAt,null);
  await expect(page.locator(`.rider[data-rider=${delivered.riderId}] .rider-waiting`)).toContainText('Last tour');
  result.checks.push('a completed tour updates the actual last-tour timer and satisfaction in the offline app');
  await page.locator('#desk-menu > summary').click();await page.locator('#open-radio-log').click();
  await expect(page.locator('#radio-history [data-action=complete] [data-speaker=rider]')).toHaveCount(1);
  await expect(page.locator('#radio-history [data-action=call]')).toHaveCount(1);
  await page.locator('#close-radio-log').click();
  result.checks.push('offline speech bubbles and current-shift radio history report confirmed offers and real deliveries');
  const snapshot=await state();await page.screenshot({path:path.join(folder,'delivery.png')});
  await app.close();app=null;
  await launch();await page.context().setOffline(true);
  await expect(page.locator('#resume-saved')).toBeVisible();await page.locator('#resume-saved').click();
  assert.deepEqual(await state(),snapshot);
  result.checks.push('closing and relaunching the app restores the exact saved shift, paused');
  await page.locator('#pause').click();
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].minimize());
  await expect.poll(()=>page.evaluate(async()=>{const {Game}=await import('/src/game.js');return Game.lastInstance.paused;})).toBe(true);
  await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.restore();w.focus();});
  result.checks.push('minimize pauses and saves the running desk');
  // Exercise the real native-menu callback and its separate sandboxed window.
  const newWindow=app.waitForEvent('window');
  await app.evaluate(({Menu})=>Menu.getApplicationMenu().items.find(i=>i.label==='Help').submenu.items[0].click());
  const sources=await newWindow;
  await expect(sources.locator('h1')).toContainText('One city');
  await sources.screenshot({path:path.join(folder,'map-sources.png')});
  const sourceClosed=sources.waitForEvent('close');
  await sources.locator('a').first().click();await sourceClosed;await page.bringToFront();
  assert.equal(app.windows().length,1);
  result.checks.push('offline map provenance returns to the original desk without creating a second game');
  // Test Chromium downloads using the same blob mechanism as the review button.
  const downloadPath=path.join(profile,'shift-export.json');
  await app.evaluate(({session},dest)=>session.defaultSession.once('will-download',(_e,item)=>item.setSavePath(dest)),downloadPath);
  await page.evaluate(async()=>{const {Game}=await import('/src/game.js');const a=document.createElement('a');a.download='shift-export.json';a.href=URL.createObjectURL(new Blob([JSON.stringify(Game.lastInstance.exportRun())],{type:'application/json'}));a.click();});
  await expect.poll(async()=>{try{return JSON.parse(await readFile(downloadPath,'utf8')).ruleset;}catch{return null;}}).toBe('berlin-dispatch-v8');
  result.checks.push('a shift record exports to a normal local file');
  assert.deepEqual(result.pageErrors,[]);assert.deepEqual(result.failedResources,[]);assert.deepEqual(result.externalRequests,[]);
  result.checks.push('no game requests to external services, missing resources or renderer errors');
  result.passed=true;
}finally{
  if(app){await page.screenshot({path:path.join(folder,'last-state.png')}).catch(()=>{});await app.close().catch(()=>{});}
  await writeFile(path.join(folder,'acceptance.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
}
